### ISSUE TITLE
Random Mobs || Horses Do No Work

### ISSUE THREAD

**Issue by aws404** [sp614x/optifine#1357]
I cannot seem to get horses to work with Random Mobs, at all. I am trying to replace the texture of a horse with a specific name. Could I be told weather this is just not working or how I could do it. Thanks

**Comment by sp614x** [comment]
Vanilla horses use randomized textures from `assets\minecraft\textures\entity\horse`.
Random mobs textures are defined per source texture. 
To make the name check work for all horses you should make configurations for all the vanilla texture variants.

**Comment by aws404** [comment]
Still having trouble getting this to work, here is my pack:
[http://aws404.site11.com/downloads/TestRandom.zip](http://aws404.site11.com/downloads/TestRandom.zip)

**Comment by sp614x** [comment]
It looks like the horse renderer is combining the base and markings texture in a dynamic texture named like `horse/hchwmo`.

**Comment by aws404** [comment]
So would creating a properties file for each one of those abbreviations work?

**Comment by sp614x** [comment]
It could be made to work, but only for the base textures, the markings will be ignored:

![image](https://user-images.githubusercontent.com/16635441/39300829-5057c6b6-494d-11e8-9784-bf24f52c8b2a.png)

**Comment by aws404** [comment]
Thanks for the info. Would be nice to see a proper fox though

**Comment by sp614x** [comment]
Using the dynamic texture name would be too complex 
7 base textures * 5 markings = 35 configurations
Also the documentation would have to be extended to list all abbreviations and how they are used.
The current solution would be to use only the base textures and ignore the markings.

**Comment by sp614x** [comment]
OptiFine 1.12.2_HD_U_D2_pre
 - fixed horse random textures (#1357) 

The test resource pack should work now.

**Comment by freakxcity** [comment]
Heyyyy! Totally sorry to be commenting on this old thread, but I'm having the same problem... I've tried just about everything I can think of and It's still not working. What was the solution we came to here?

**Comment by LeBonhommeBleu** [comment]
Hey! same here ^^'
