### ISSUE TITLE
Does not launch with Java 10

### ISSUE THREAD

**Issue by txtsd** [sp614x/optifine#1376]
```
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp -Dswing.defaultlaf.sun.java.swing.plaf.gtk.GTKLookAndFeel
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

```
┌[txtsd@dungeon-of-data]─[~/minecraft]                                                                                                            [18-04-28 14:07:58]
└─▶ java -jar Minecraft.jar                                                                                                                                           
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=gasp -Dswing.defaultlaf.sun.java.swing.plaf.gtk.GTKLookAndFeel
Bootstrap (v5)
Current time is Apr 28, 2018, 2:08:42 PM
System.getProperty('os.name') == 'Linux'
System.getProperty('os.version') == '4.16.0-rc7-d7a76c6d226e'
System.getProperty('os.arch') == 'amd64'
System.getProperty('java.version') == '10.0.1'
System.getProperty('java.vendor') == 'Oracle Corporation'
System.getProperty('sun.arch.data.model') == '64'

Looking for update
Downloading: https://s3.amazonaws.com/Minecraft.Download/launcher/launcher.pack.lzma
Got reply in: 948ms
No update found.
Reversing LZMA on /home/txtsd/.minecraft/launcher.pack.lzma to /home/txtsd/.minecraft/launcher.pack
Unpacking /home/txtsd/.minecraft/launcher.pack to /home/txtsd/.minecraft/launcher.jar
Cleaning up /home/txtsd/.minecraft/launcher.pack
Starting launcher.
[14:08:46 INFO]: Minecraft Launcher 1.6.84-j (through bootstrap 5) started on linux...
[14:08:46 INFO]: Current time is Apr 28, 2018, 2:08:46 PM
[14:08:46 INFO]: System.getProperty('os.name') == 'Linux'
[14:08:46 INFO]: System.getProperty('os.version') == '4.16.0-rc7-d7a76c6d226e'
[14:08:46 INFO]: System.getProperty('os.arch') == 'amd64'
[14:08:46 INFO]: System.getProperty('java.version') == '10.0.1'
[14:08:46 INFO]: System.getProperty('java.vendor') == 'Oracle Corporation'
[14:08:46 INFO]: System.getProperty('sun.arch.data.model') == '64'
[14:08:46 INFO]: proxy == DIRECT
[14:08:46 INFO]: Refreshing local version list...
[14:08:46 INFO]: Refreshing remote version list...
[14:08:47 INFO]: Refresh complete.
[14:08:47 INFO]: Loaded 4 profile(s); selected 'OptiFine'
[14:08:47 INFO]: Refreshing auth...
[14:08:47 INFO]: Logging in with access token
[14:08:52 INFO]: Getting syncinfo for selected version
[14:08:52 INFO]: Queueing library & version downloads
[14:08:52 INFO]: Download job 'Version & Libraries' started (16 threads, 37 files)
[14:08:52 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar for job 'Version & Libraries'... (try 0)
[14:08:52 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar for job 'Version & Libraries'... (try 0)
[14:08:52 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar for job 'Version & Libraries'... (try 0)
[14:08:52 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar for job 'Version & Libraries'... (try 0)
[14:08:52 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar for job 'Version & Libraries'... (try 0)
[14:08:52 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar for job 'Version & Libraries'... (try 0)
[14:08:52 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar for job 'Version & Libraries'... (try 0)
[14:08:52 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar for job 'Version & Libraries'... (try 0)
[14:08:52 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar for job 'Version & Libraries'... (try 0)
[14:08:52 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar for job 'Version & Libraries'... (try 0)
[14:08:52 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar for job 'Version & Libraries'... (try 0)
[14:08:52 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/com/mojang/realms/1.10.19/realms-1.10.19.jar for job 'Version & Libraries'... (try 0)
[14:08:52 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar for job 'Version & Libraries'... (try 0)
[14:08:52 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar for job 'Version & Libraries'... (try 0)
[14:08:52 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar for job 'Version & Libraries'... (try 0)
[14:08:52 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Download job 'Resources' skipped as there are no files to download
[14:08:56 INFO]: Job 'Resources' finished successfully (took 0:00:00.000)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/com/mojang/realms/1.10.19/realms-1.10.19.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/optifine/OptiFine/1.12.2_HD_U_D1/OptiFine-1.12.2_HD_U_D1.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Attempting to download /home/txtsd/.minecraft/versions/1.12.2-OptiFine_HD_U_D1/1.12.2-OptiFine_HD_U_D1.jar for job 'Version & Libraries'... (try 0)
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:56 INFO]: Finished downloading /home/txtsd/.minecraft/versions/1.12.2-OptiFine_HD_U_D1/1.12.2-OptiFine_HD_U_D1.jar for job 'Version & Libraries': Local file matches hash, using that
[14:08:57 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar for job 'Version & Libraries': Remote checksum matches local file
[14:08:57 INFO]: Finished downloading /home/txtsd/.minecraft/libraries/optifine/OptiFine/1.12.2_HD_U_D1/OptiFine-1.12.2_HD_U_D1.jar for job 'Version & Libraries': Couldn't find a checksum so assuming our copy is good
[14:08:57 INFO]: Job 'Version & Libraries' finished successfully (took 0:00:05.254)
[14:08:57 INFO]: Launching game
[14:08:57 INFO]: Unpacking natives to /home/txtsd/.minecraft/versions/1.12.2-OptiFine_HD_U_D1/1.12.2-OptiFine_HD_U_D1-natives-129956238382534
[14:08:57 INFO]: Launching in /home/txtsd/.minecraft
[14:08:57 INFO]: Half command: /usr/lib/jvm/java-10-openjdk/bin/java -Xmx4G -XX:-UseAdaptiveSizePolicy -Xmn256M -Djava.library.path=/home/txtsd/.minecraft/versions/1.12.2-OptiFine_HD_U_D1/1.12.2-OptiFine_HD_U_D1-natives-129956238382534 -Dminecraft.launcher.brand=java-minecraft-launcher -Dminecraft.launcher.version=1.6.84-j -Dminecraft.client.jar=/home/txtsd/.minecraft/versions/1.12.2-OptiFine_HD_U_D1/1.12.2-OptiFine_HD_U_D1.jar -cp /home/txtsd/.minecraft/libraries/optifine/OptiFine/1.12.2_HD_U_D1/OptiFine-1.12.2_HD_U_D1.jar:/home/txtsd/.minecraft/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar:/home/txtsd/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar:/home/txtsd/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:/home/txtsd/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:/home/txtsd/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:/home/txtsd/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:/home/txtsd/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:/home/txtsd/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/home/txtsd/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/home/txtsd/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/home/txtsd/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:/home/txtsd/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/home/txtsd/.minecraft/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar:/home/txtsd/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar:/home/txtsd/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/txtsd/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:/home/txtsd/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/home/txtsd/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/home/txtsd/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/home/txtsd/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/home/txtsd/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar:/home/txtsd/.minecraft/libraries/com/mojang/realms/1.10.19/realms-1.10.19.jar:/home/txtsd/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/home/txtsd/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/home/txtsd/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/home/txtsd/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/home/txtsd/.minecraft/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar:/home/txtsd/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:/home/txtsd/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:/home/txtsd/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar:/home/txtsd/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar:/home/txtsd/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar:/home/txtsd/.minecraft/versions/1.12.2-OptiFine_HD_U_D1/1.12.2-OptiFine_HD_U_D1.jar net.minecraft.launchwrapper.Launch
[14:08:57 INFO]: Looking for orphaned versions to clean up...
[14:08:57 INFO]: Looking for old natives & assets to clean up...
[14:08:57 ERROR]: java.io.IOException: Stream closed
[14:08:57 ERROR]: Game ended with bad state (exit code 1)
[14:08:57 INFO]: Ignoring visibility rule and showing launcher due to a game crash
[14:08:57 INFO]: Deleting /home/txtsd/.minecraft/versions/1.12.2-OptiFine_HD_U_D1/1.12.2-OptiFine_HD_U_D1-natives-129956238382534
[14:09:15 INFO]: Window closed, shutting down.
[14:09:15 INFO]: Halting executors
[14:09:15 INFO]: Awaiting termination.
[14:09:15 INFO]: Goodbye.
```

**Comment by LightWayUp** [comment]
This isn't an issue related to OptiFine, but launchwrapper ([LegacyLauncher](https://github.com/Mojang/LegacyLauncher)). Since Java 9, the AppClassLoader is no longer an URLClassLoader, hence the ClassCastException. Refer to [this issue](https://github.com/Mojang/LegacyLauncher/issues/20), and [this closed Pull Request](https://github.com/Mojang/LegacyLauncher/pull/11). Since the module system isn't going away in Java, and Mojang seems to be unwilling to fix LegacyLauncher, OptiFine will need to find a new way to launch.

**Comment by txtsd** [comment]
Thanks for the insight. So it doesn't look like it'll get fixed until Mojang decides Java 10 and the new class loading mechanism is worth it.

**Comment by sp614x** [comment]
This is a launchwrapper problem.

**Comment by Dushess** [comment]
Come to the -dark side- other launcher.

**Comment by LightWayUp** [comment]
@Dushess Oh... actually LegacyLauncher isn't a "Minecraft launcher" normally talked about. It's used to launch legacy versions of Minecraft, as well as mods like Forge and OptiFine.
If you look at the description, it says "Hacky code to launch our old versions", as it uses [Reflection](http://www.oracle.com/technetwork/articles/java/javareflection-1536171.html) and even [ASM](http://asm.ow2.io/) ( a Java bytecode manipulation framework ) to make this possible.
Forge, which also faces this issue, is working on their new loading/launching system. See [this discussion](https://github.com/MinecraftForge/MinecraftForge/issues/3935). If OptiFine keeps using launchwrapper, it'll never support Java 9 and above, where Project Jigsaw is in place.

**Comment by sp614x** [comment]
Updated launchwrapper by Runemoro, should be compatible with Java 8,9,10:
[NewerJavaCompatibility.zip](https://github.com/sp614x/optifine/files/2342731/NewerJavaCompatibility.zip)

**Comment by SylveonBottle** [comment]
Confirming that the NewerJavaCompatibility.zip above, when installed, adds Java 10.0.2 compatibility with Optifine.

Would be interesting if Optifine could detect what java version the user is using, and install the above launchwrapper version automatically. Maybe a checkbox for java10 compatibility or something.

**Comment by LightWayUp** [comment]
@SylveonBottle No need. **Java 9 and onward**, including versions with and without long term support, will retain the change ( AppClassLoader not being a URLClassLoader ). I've tested the new modified LegacyLauncher against Java 8, 9, 10 and 11. The fix is **backward compatible** at least to Java 8, meaning the fix always works with any still-supported Java version. OptiFine can manually include this version of LegacyLauncher, extract it from the JAR when installing, and use it as the dependency. The change requires tweaking the launchwrapper version in the JSON file, from "1.12" to "2.0".

From this :
```json
"libraries": [
    {
      "name": "net.minecraft:launchwrapper:1.12"
    }
]```To this :
```json
"libraries": [
    {
      "name": "net.minecraft:launchwrapper:2.0"
    }
]```( 2.0 is the manually included one, it's not official and not available on Mojang's servers. )

**Comment by SylveonBottle** [comment]
Confirming that the above patch is compatible with Java 11 LTS.

![image](https://user-images.githubusercontent.com/17802843/46175060-50a64600-c270-11e8-82ee-0db4787f67e8.png)

**Comment by hacker1024** [comment]
The above patch works for me, as well.
Note: On MultiMC, the new library can be used by changing it in the OptiFine patch JSON file.

**Comment by gendalv** [comment]
can't launch with java 11

**Comment by cfbauer** [comment]
Any chance someone could explain what to do with the launchwrapper.jar file?

**Comment by ProfessorStrawberry** [comment]
> 
> 
> Any chance someone could explain what to do with the launchwrapper.jar file?

after you have installed optifine you go to `C:\Users\_Username_\AppData\Roaming\.minecraft`


In the rar archive there are 2 folders.

First folder inside archive has the structure: `libraries\net\minecraft\launchwrapper\2.0`

Copy the "2.0" folder to `C:\Users\_Username_\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper`


Second folder inside archive has the structure: `versions\1.13-OptiFine_HD_U_E3_beta3`

Look at the code inside the 1.13-OptiFine_HD_U_E3_beta3.json file.

There is a line saying  `"name": "net.minecraft:launchwrapper:2.0"`

Now go to `C:\Users\_Username_\AppData\Roaming\.minecraft\versions`
and depending on your version number of optifine open the optifine folder, in my case `1.13.2-OptiFine_HD_U_E6`.

Open _1.13.2-OptiFine_HD_U_E6.json_ and look for the line `net.minecraft:launchwrapper:1.12` and replace it with `"name": "net.minecraft:launchwrapper:2.0"`.

Save it. In my case and I really don't know why, I had to make the file read-only to apply the changes otherwise the line would say 1.12 again.

Now you can launch Minecraft with Java 11 and Optifine.

**Comment by SylveonBottle** [comment]
Confirming that the above patch is compatible with Java 12.

![image](https://user-images.githubusercontent.com/17802843/55287564-3446ab80-5370-11e9-9168-4868caa823a7.png)

**Comment by HopefulFire** [comment]
Doesn't work on Optifine e7. It will keep deleting the json file and resetting it to default.

**Comment by HopefulFire** [comment]
Error details: File hash should be 6d7cc9b1a2a03e4da0a5269f00c61909bd1eb75c but was f50d6d9f4f13e2c457d5aad75ce441b969672e3f Permission denied
Filename on disk: 1.13.2-OptiFine_HD_U_E7.json
Path: /home/jade/.minecraft/versions/1.13.2-OptiFine_HD_U_E7/1.13.2-OptiFine_HD_U_E7.json
Exists: file

**Comment by HopefulFire** [comment]
That's after setting the whole directory to read only! Why does the configuration file need to be hash checked? Doesn't that defeat the purpose of a configuration file?

**Comment by HopefulFire** [comment]
I guess I am installing java 8!

**Comment by SylveonBottle** [comment]
@HopefulFire 
Please make sure you close the minecraft launcher before saving the file, then re-open it afterwards.  
If you do not do this, the launcher will not "accept" the changes and may even revert them.

I can confirm E7 works with Java 12.  
![image](https://user-images.githubusercontent.com/17802843/55484547-49c90900-55ee-11e9-8b92-b4a289e2a9d1.png)

**Comment by LightWayUp** [comment]
@HopefulFire I can confirm that it *does* work with 1.13.2 OptiFine E7 and Java 12.
![Screenshot of debug information](https://i.imgur.com/MKve6ku.png)

**Comment by sp614x** [comment]
@HopefulFire the launcher tries to check the hash of everything, but it can't update custom profiles
Make sure the launcher is closed when modifying the JSON, otherwise it will overwrite it on close.

**Comment by pressRtowin** [comment]
> > Any chance someone could explain what to do with the launchwrapper.jar file?
> 
> after you have installed optifine you go to `C:\Users\_Username_\AppData\Roaming\.minecraft`
> 
> In the rar archive there are 2 folders.
> 
> First folder inside archive has the structure: `libraries\net\minecraft\launchwrapper\2.0`
> 
> Copy the "2.0" folder to `C:\Users\_Username_\AppData\Roaming\.minecraft\libraries\net\minecraft\launchwrapper`
> 
> Second folder inside archive has the structure: `versions\1.13-OptiFine_HD_U_E3_beta3`
> 
> Look at the code inside the 1.13-OptiFine_HD_U_E3_beta3.json file.
> 
> There is a line saying `"name": "net.minecraft:launchwrapper:2.0"`
> 
> Now go to `C:\Users\_Username_\AppData\Roaming\.minecraft\versions`
> and depending on your version number of optifine open the optifine folder, in my case `1.13.2-OptiFine_HD_U_E6`.
> 
> Open _1.13.2-OptiFine_HD_U_E6.json_ and look for the line `net.minecraft:launchwrapper:1.12` and replace it with `"name": "net.minecraft:launchwrapper:2.0"`.
> 
> Save it. In my case and I really don't know why, I had to make the file read-only to apply the changes otherwise the line would say 1.12 again.
> 
> Now you can launch Minecraft with Java 11 and Optifine.

Any way to do this with a MultiMC + Forge + Optifine setup (1.12.2)? I found the correct location for the libraries but I don't have an optifine json, and I can't seem to get forge to use it either. I think it tries to pull it from the minecraft server so it says it doesn't exist or something if I try to modify it to use the 2.0 version.

**Comment by HopefulFire** [comment]
Yeah I figured it out, thanks. I found it easier to install Java 8 alongside Java 9+, and just use multimc. It has an easy option to specify Java versions, is faster than the default launcher, can load twitch modpacks, and doesn't need to be manually updated or tweaked.
Also, not really relevant, but I stopped trying to use Java 9+ because I experienced crashes on clients when opening books if they were using Java 8 on a Java 9+ server. This is a vanilla issue. There is no real reason to use Java 9+ for clients either, because this will just cause issues later (if your friend wants to jump on lan). I would recommend telling people to install Java 8 rather than telling them a hacky process to use the Java 9+ on their system. Multimc is simple and has an easy gui. All that needs to be done after installing multimc is to install Java 8, then choose the Java version in multimc. No need to change system defaults. I wish I had known about this sooner.

**Comment by HopefulFire** [comment]
Also, not sure if the crashing when opening books thing is still an issue; knowing Mojang probably. I don't have the link to the bug, sorry.

**Comment by HopefulFire** [comment]
It is in 1.12.2

**Comment by sp614x** [comment]
Fixed installer to install launchwrapper-2.0
All new versions would use the new installer.

**Comment by KadduBaba** [comment]
> Fixed installer to install launchwrapper-2.0
> All new versions would use the new installer.

Well, im using 1.14.3 and it still crashes. I have checked everything and it seems to tally. idk what is the issue.

**Comment by SylveonBottle** [comment]
AdoptOpenJDK 13, 1.14.4_HD_U_F4_pre6. Working perfectly.
![2019-10-02_01 43 19](https://user-images.githubusercontent.com/17802843/66023208-150f0f00-e4b6-11e9-86a9-bc74ded04e5e.png)

**Comment by SylveonBottle** [comment]
AdoptOpenJDK JRE 15, OptiFine_1.16.3_HD_U_G3. Working perfectly.

![2020-09-17_08 04 25](https://user-images.githubusercontent.com/17802843/93474685-4fd3a800-f8bd-11ea-8ab5-54254930e6d4.png)
