### ISSUE TITLE
Crash when launching OptiFine 1.13 HD U E3 alpha8

### ISSUE THREAD

**Issue by DjGamerDz** [sp614x/optifine#1635]
(original launcher) the launcher log :
[launcher_log.txt](https://github.com/sp614x/optifine/files/2280565/launcher_log.txt)
the launcher log (from tlauncher):
https://pastebin.com/QeEY3xsh
the launchers don't give me a crash report.

**Comment by xfl03** [comment]
Please use OptiFine inner GUI installer to install it.
It look like you did not add TweakClass in game argument.

**Comment by DjGamerDz** [comment]
no i install it from optifine installer

**Comment by xfl03** [comment]
Could you upload your version profile here?

**Comment by DjGamerDz** [comment]
ITS WORKS NOW
AFTER I REINSTALL IT

**Comment by skmedix** [comment]
Replace `1.13.json` content with: 
[1.13.json](https://gist.githubusercontent.com/skmedix/220788300ac6b74ea144fdbd58418e5d/raw/8a6cd7ccd5dd1ef1fdd622891eda0f2d761a6a1e/1.13.json)
And replace `1.13-OptiFine_HD_U_E3_alpha8.json` content with:
[1.13-OptiFine_HD_U_E3_alpha8.json](https://gist.githubusercontent.com/skmedix/a2907114a54e8568e97a9db493691a54/raw/e3e084a31ed2e17ee3fad720b3fb59c35f17f2be/1.13-OptiFine_HD_U_E3_alpha8.json)

Or just drop the content of this zip to `.minecraft`.
[old-launcher-fix.zip](https://github.com/sp614x/optifine/files/2291915/old-launcher-fix.zip)

**Comment by ASFdirrt** [comment]
The optifine 1.13 alpha 9 is out, how can i fix this crash?

**Comment by GarethPW** [comment]
I'm getting the following.

```
Error: Could not find or load main class net.minecraft.launchwrapper.Launch
```

This has been the case with both alpha8 and alpha10. Replacing the JSON files does nothing.

**Comment by KaelemGaen** [comment]
Error seems to exist still in Alpha10 with the I'm guessing old Launcher even the latest version of the Old launcher 1.6.91

**Comment by skmedix** [comment]
The whole situation is caused because of bad version file serialization [MCL-8475](https://bugs.mojang.com/browse/MCL-8475).

I was actually testing these things **a lot**. And I've got two errors, that I saw in a few issues.

1. `Error: Could not find or load main class net.minecraft.launchwrapper.Launch`
This error appeared when the launcher didn't read game arguments from 1.13.json file, and game arguments wasn't inherited for OF.

2. `Calling tweak class net.minecraft.launchwrapper.VanillaTweaker
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor`
This is not an issue with a lauchwrapper as somebody said in different issue. That error means that lauchwrapper didn't get OF's tweak class arguments.

**Comment by igooreqq** [comment]
Someone could repair an Optifine 1.13 beta1 on sk launcher 3.0??

**Comment by ASFdirrt** [comment]
How can i fix it with beta2?

**Comment by KaelemGaen** [comment]
Alright let me see if I can find it, the Launcher.jar in my .minecraft seems to load up as 1.6.73-j when I launch it directly need to see where my shortcut points.

**Comment by GarethPW** [comment]
I find that every time I open my Minecraft launcher, it overwrites @skmedix's fixes. I've resorted to setting `1.13.json` as read-only, which isn't pretty but seems to have fixed it. Is it possible to move some of the data in `1.13.json` to Optifine's respective JSON file which isn't overwritten?

**Comment by skmedix** [comment]
@GarethPW 
[1.13-OptiFine_HD_U_E3_beta3.json](https://gist.githubusercontent.com/skmedix/c2722c41555037f9d7c12073ed670013/raw/6f7479524d46e4fbb6e86d479dc84fc8d433040f/1.13-OptiFine_HD_U_E3_beta3.json)
This file is not using `1.13.json`, nothing is inherited.

**Comment by GarethPW** [comment]
Unfortunately, now I have to set *that* file to read-only instead. I suppose that's better though for the time being.

**Comment by sp614x** [comment]
Fixed JSON launch arguments to use primitive strings as suggested by @skmedix. This should make it compatible to both the old and the new laucher:
```
  "arguments": {
    "game": [
          "--tweakClass",
          "optifine.OptiFineTweaker"
    ]
  }
```

**Comment by sp614x** [comment]
Fixed in beta4.

**Comment by Nik-mmzd** [comment]
@sp614x seems like it is not fixed O_o
Just downloaded and installed OptiFine 1.13.1_HD_U_E3_**beta5** (using Install button in installer)
got this 1.13.1-OptiFine_HD_U_E3_beta5.json:
```
{
  "id": "1.13.1-OptiFine_HD_U_E3_beta5",
  "inheritsFrom": "1.13.1",
  "time": "2018-09-04T20:01:37+03:00",
  "releaseTime": "2018-09-04T20:01:37+03:00",
  "type": "release",
  "libraries": [
    {
      "name": "optifine:OptiFine:1.13.1_HD_U_E3_beta5"
    },
    {
      "name": "net.minecraft:launchwrapper:1.12"
    }
  ],
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "minecraftArguments": "--username ${auth_player_name} --version ${version_name} --gameDir ${game_directory} --assetsDir ${assets_root} --assetIndex ${assets_index_name} --uuid ${auth_uuid} --accessToken ${auth_access_token} --userType ${user_type} --versionType ${version_type}  --tweakClass optifine.OptiFineTweaker"
}
```
and successfully got this error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/ClassVisitor 	at java.lang.Class.getDeclaredConstructors0(Native Method) 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) 	at java.lang.Class.getConstructor0(Class.java:3075) 	at java.lang.Class.newInstance(Class.java:412) 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) 	at net.minecraft.launchwrapper.VanillaTweaker.injectIntoClassLoader(VanillaTweaker.java:16) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.ClassVisitor 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	... 8 more
```
in official launcher:
![image](https://user-images.githubusercontent.com/19509291/45046186-16d18d80-b07e-11e8-8db9-741038e1455f.png)

Also, there was NO `arguments` array in OptiFine JSON at all

**BUT**
After I got this crash I tried to reinstall OptiFine (**without** installer re-downloading) and got **other** JSON:
```
{
  "id": "1.13.1-OptiFine_HD_U_E3_beta5",
  "inheritsFrom": "1.13.1",
  "time": "2018-09-04T20:12:52+03:00",
  "releaseTime": "2018-09-04T20:12:52+03:00",
  "type": "release",
  "libraries": [
    {
      "name": "optifine:OptiFine:1.13.1_HD_U_E3_beta5"
    },
    {
      "name": "net.minecraft:launchwrapper:1.12"
    }
  ],
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "minimumLauncherVersion": "21",
  "arguments": {
    "game": [
      "--tweakClass",
      "optifine.OptiFineTweaker"
    ]
  }
}
```
And all works well.
But why it exported wrong JSON at first installation? O_o

Maybe you'll merge "legacy" and "current" version JSON into one profile?

**Comment by Polda18** [comment]
Well, similarily to the previous, I got this JSON:

```json
{
  "id": "1.13.1-OptiFine_HD_U_E3_pre1",
  "inheritsFrom": "1.13.1",
  "time": "2018-09-19T21:50:05+02:00",
  "releaseTime": "2018-09-19T21:50:05+02:00",
  "type": "release",
  "libraries": [
    {
      "name": "optifine:OptiFine:1.13.1_HD_U_E3_pre1"
    },
    {
      "name": "net.minecraft:launchwrapper:1.12"
    }
  ],
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "minimumLauncherVersion": "21",
  "arguments": {
    "game": [
      "--tweakClass",
      "optifine.OptiFineTweaker"
    ]
  }
}
```

However, it doesn't work. I had `beta5` previously installed, and it decided to not work just today. I changed nothing, no resourcepacks were actually used, and yet it crashed with rather weird report, that texture doesn't fit blocks or something like that. So I decided to install `pre1` release, and nothing changed. Installed it several times, nothing. So I went and checked the JSON. Appears to be exact same format as the one fixing the bug. But it's not. What happened?

**Comment by Nik-mmzd** [comment]
@Polda18 it'll be better if you'll open a new issue and attach crash report (not the version JSON) there
