### ISSUE TITLE
CEM support for 1.13 mobs

### ISSUE THREAD

**Issue by MrConfusioned** [sp614x/optifine#1822]

**Comment by D3monPixel** [comment]
The Illusioner that was added in 1.12 as a command-only hostile mob is also still missing CEM functionality, despite random entity features fully working for them.

**Comment by sp614x** [comment]
It would be nice to have a list of all mobs that need CEM added.

**Comment by D3monPixel** [comment]
From 1.12:
illusioner ("illusion_illager" back then if a backport with updates made in 1.13 OF is made for 1.12)
From 1.13:
cod
salmon
turtle
tropical_fish
pufferfish (3 states)
dolphin
drowned
phantom

**Comment by MrConfusioned** [comment]
this is off topic but you didnt update the name of the red mushroom on the mooshrooms back to fit with the flattening you still have to put mushroom_red not red_mushroom

**Comment by MrConfusioned** [comment]
How about the new horse model can you use cem on that

**Comment by Glopeur** [comment]
Adding Trident entity to CEM could be a good thing too.
![trident](https://user-images.githubusercontent.com/35874673/46249970-8abf4580-c432-11e8-9441-ca81b0f34bc3.png)

**Comment by sp614x** [comment]
Added illusioner, fixed names for vindicator, evoker and evoker_fangs.

**Comment by sp614x** [comment]
Fixed mooshroom back mushroom texture to "textures/entity/cow/red_mushroom.png"

**Comment by MushirMickeyJoe** [comment]
Not sure if this needs its own issue, but the 1.14 mobs still need custom CEM added as well. Specifically mobs like the ravager would be amazing

I also just realized that turtles aren't supported yet, jpto.

**Comment by mexbotdude** [comment]
its been almost a year, we are still missing most of the new CEM models, not sure how complex it its but it would be nice if they could add the Phantom and Ravager at least

**Comment by Thorolhugil** [comment]
I went to make a phantom CEM model and realised that there's no current support, so I've made a list of mobs that aren't currently supported:

- Cat
- Cod
- Fox
- Panda
- Phantom
- Pufferfish
- Salmon
- Trader Llama (? Is this just part of the regular llama model or is it classified as its own thing?)
- Tropical Fish (small)
- Tropical Fish (large)
- Turtle
--
- Pillager
- Ravager
- Wandering Trader

**Comment by KKMNNOIR** [comment]
I want a bell added too.

**Comment by sp614x** [comment]
Cod, salmon, pufferfish and tropical fish (no color/pattern support) were added in 1.14.4 F4 previews.

**Comment by sp614x** [comment]
Added CEM for cat, fox, panda, phantom, pillager, ravager and turtle.
Coming in next 1.14.4 preview.

**Comment by Locxes** [comment]
Another bug that their original head stay still even the cem for head is false, there's another bug for villagers. Great work and thanks for the witch fix.

**Comment by Locxes** [comment]
Looks like pillager still do not suppot the cem yet

**Comment by sp614x** [comment]
The pillager should generally work. 
However it shares the model with the villager which is not 100% working yet, so there may be something broken.

**Comment by Locxes** [comment]
What's the name for the pillager in order to work I've tried it's direct name but nothing changed

**Comment by sp614x** [comment]
The pillager is loaded from `pillager.jem`.

**Comment by Locxes** [comment]
Thanks for the error log, my pillager has been fixed

**Comment by sp614x** [comment]
Test resource pack?
Only the CEM folder would be enough

**Comment by Locxes** [comment]
[Player+Villagers+v1.2 (2).zip](https://github.com/sp614x/optifine/files/3792186/Player%2BVillagers%2Bv1.2.2.zip)

**Comment by Locxes** [comment]
[illusioner.zip](https://github.com/sp614x/optifine/files/3798554/illusioner.zip)
i sent the wrong zip, that one's a failure, use this instead
