### ISSUE TITLE
[1.7.10] Custom skies work on low render distances, but they're cut off

### ISSUE THREAD

**Issue by Revemohl** [sp614x/optifine#2257]
I know how old 1.7.10 is by now, but since this problem that's been bugging me for a while doesn't happen on modern versions (I just checked) and I've yet to see anyone else bring it up I figured I should report it.

As said in the title, custom skies technically work on 1.7.10 at any render distance ever since OptiFine 1.7.10_HD_U_E3, but they have this rendering issue where they feel like they're in some sort of box and don't show up completely:

![image](https://i.imgur.com/o4HvvT8.png)
Normal weather
![image](https://i.imgur.com/WcAegur.png)
More visible during rain

Both screenshots taken using [Pixel Reality Atmosphere](https://minecraft.curseforge.com/projects/pixel-reality-atmosphere) at 4 render distance, using Optifine 1.7.10_HD_U_E7. Fast/fancy graphics doesn't seem to affect this, neither does any other setting.

**Comment by sp614x** [comment]
This was fixed at some point in 1.8.

**Comment by tyrael93** [comment]
That's nice, but the problem persists in minecraft 1.7. Is this ever gonna get fixed? 
![2021-04-27_17 41 12](https://user-images.githubusercontent.com/5557920/116273212-dae51c80-a781-11eb-84ba-4ea908592196.png)
If not, just close the issue.

**Comment by tyrael93** [comment]
And lo, it did.
