### ISSUE TITLE
LWJGL Crash with OptiFine.

### ISSUE THREAD

**Issue by LewisTehMinerz** [sp614x/optifine#2411]
```
[14:19:08] [main/INFO]: [OptiFine] *** Reloading textures ***
[14:19:08] [main/INFO]: [OptiFine] Resource packs: Default
[14:19:16] [Server-Worker-2/WARN]: Codepoint '1ed0' declared multiple times in minecraft:textures/font/accented.png
FATAL ERROR in native method: Thread[Server-Worker-2,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11C.nglTexImage2D(Native Method)
	at org.lwjgl.opengl.GL11C.glTexImage2D(GL11C.java:1753)
	at org.lwjgl.opengl.GL11.glTexImage2D(GL11.java:7055)
	at com.mojang.blaze3d.platform.GlStateManager.texImage2D(SourceFile:493)
	at net.optifine.util.TextureUtils.detectGLMaximumTextureSize(TextureUtils.java:695)
	at net.optifine.util.TextureUtils.getGLMaximumTextureSize(TextureUtils.java:682)
	at dui.a(AtlasTexture.java:332)
	at dvd.b(SourceFile:29)
	at dvd.a(SourceFile:11)
	at xg.b(SourceFile:11)
	at xg$$Lambda$1625/1473829090.get(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

Not sure what's causing this. A search on Google shows this happening in *development* environments (most commonly Gradle), but not in production. This is 1.14.2. If I remove OptiFine from my game, it starts up perfectly fine.

Sidenote: Patching into the game through MultiMC, might be causing it? Most likely not, but still a possibility.

**Comment by LewisTehMinerz** [comment]
It appears that using the extracted version of OptiFine as the library in MultiMC makes it work.

**Comment by sp614x** [comment]
Most probably the "com.mojang.blaze3d.*" patches are not being properly applied.
Something to do with MultiMC.

**Comment by poqdavid** [comment]
I had the same problem with 1.14.2_HD_U_F1_pre9 and the only way it worked was to extract the optifine but this was never a problem before

**Comment by peterix** [comment]
Yep. Optifine is no longer loadable as a library with launchwrapper.

**Comment by peterix** [comment]
Premade instance with the problem for easy testing:
[1.14.2-OptiFine.zip](https://github.com/sp614x/optifine/files/3265260/1.14.2-OptiFine.zip)

**Comment by sp614x** [comment]
The `optifne.OptiFineTweaker` works with the vanilla launcher:
```
{
  "id": "1.14.2-OptiFine_HD_U_F1_pre9",
  "inheritsFrom": "1.14.2",
  "time": "2019-06-04T17:52:01+02:00",
  "releaseTime": "2019-06-04T17:52:01+02:00",
  "type": "release",
  "libraries": [
    {
      "name": "optifine:OptiFine:1.14.2_HD_U_F1_pre9"
    },
    {
      "name": "net.minecraft:launchwrapper:1.12"
    }
  ],
  "mainClass": "net.minecraft.launchwrapper.Launch",
  "minimumLauncherVersion": "21",
  "arguments": {
    "game": [
      "--tweakClass",
      "optifine.OptiFineTweaker"
    ]
  }
}
```

**Comment by peterix** [comment]
So, this is about classpath order. In previous versions of OptiFine, it was possible to have the optifine jar further down the classpath. Now it wants to be in the front for some odd reason.

Working classpath order:
```
libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
instances/1.14.2-OptiFine/libraries/preview_OptiFine_1.14.2_HD_U_F1_pre9.jar
libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
libraries/com/mojang/patchy/1.1/patchy-1.1.jar
libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
libraries/com/google/guava/guava/21.0/guava-21.0.jar
libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
libraries/com/mojang/realms/1.14.16/realms-1.14.16.jar
libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
libraries/com/mojang/minecraft/1.14.2/minecraft-1.14.2-client.jar
```

Not working classpath order:
```
libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
libraries/com/mojang/patchy/1.1/patchy-1.1.jar
libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
libraries/com/google/guava/guava/21.0/guava-21.0.jar
libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
libraries/com/mojang/realms/1.14.16/realms-1.14.16.jar
libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
instances/1.14.2-OptiFine/libraries/preview_OptiFine_1.14.2_HD_U_F1_pre9.jar
libraries/com/mojang/minecraft/1.14.2/minecraft-1.14.2-client.jar
```

Are you overriding something in LWJGL?

**Comment by peterix** [comment]
This also works... so it's not LWJGL, but something in the other Minecraft libraries:
```
libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar
libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar
libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar
libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar
libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar
libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar
libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
instances/1.14.2-OptiFine/libraries/preview_OptiFine_1.14.2_HD_U_F1_pre9.jar
libraries/com/mojang/patchy/1.1/patchy-1.1.jar
libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
libraries/com/google/guava/guava/21.0/guava-21.0.jar
libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar
libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
libraries/com/mojang/realms/1.14.16/realms-1.14.16.jar
libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
libraries/com/mojang/minecraft/1.14.2/minecraft-1.14.2-client.jar
```

**Comment by mindforger** [comment]
do you have mods installed!? i remember an issue in Immersive Engineering where class loading was thrown out of order also but through an offender that could not be identified

**Comment by peterix** [comment]
Obviously not. I am testing with OF only. Adding more stuff into the mix would just add more noise.

**Comment by peterix** [comment]
Actually, it wasn't overriding the mainClass when moved and that's why it 'worked'. So, disregard the above.

This might be an OpenGL driver issue.

**Comment by peterix** [comment]
```
[0607/135749:INFO:GameCallbacks.cpp(198)] game/cvk (main) info LWJGL Version: 3.2.1 build 12

[0607/135750:INFO:GameCallbacks.cpp(198)] game/Config (main) info [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.ModelLoader

[0607/135750:INFO:GameCallbacks.cpp(198)] game/com.mojang.text2speech.NarratorLinux (main) info Narrator library successfully loaded

[0607/135750:INFO:GameCallbacks.cpp(198)] game/com.mojang.realmsclient.plugin.RealmsPluginImpl (main) info Built for minecraft version 1.14.2

[0607/135750:INFO:GameCallbacks.cpp(198)] game/Config (main) info [OptiFine] *** Reloading textures ***

[0607/135750:INFO:GameCallbacks.cpp(198)] game/Config (main) info [OptiFine] Resource packs: Default

[0607/135759:INFO:GameCallbacks.cpp(198)] launcher/launcher (main) info 
FATAL ERROR in native method: Thread[Server-Worker-5,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11C.nglTexImage2D(Native Method)
	at org.lwjgl.opengl.GL11C.glTexImage2D(GL11C.java:1753)
	at org.lwjgl.opengl.GL11.glTexImage2D(GL11.java:7055)
	at com.mojang.blaze3d.platform.GlStateManager.texImage2D(SourceFile:493)
	at net.optifine.util.TextureUtils.detectGLMaximumTextureSize(TextureUtils.java:695)
	at net.optifine.util.TextureUtils.getGLMaximumTextureSize(TextureUtils.java:682)
	at dui.a(AtlasTexture.java:332)
	at dix.lambda$reload$3(ParticleManager.java:186)
	at dix$$Lambda$1732/1354373599.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Crashes with vanilla launcher.

This is on linux with the `nvidia 430.14` driver.

**Comment by peterix** [comment]
It is also entirely possible that this is multiple problems...

**Comment by sp614x** [comment]
The difference in 1.14 compared to 1.13 is that the `com.mojang.blaze3d` package is now separated from the rest of the MC code.
With vanilla launcher the tweaker has problems to overwrite only some of the `com.mojang.blaze3d` classes. 
```
java.lang.SecurityException: class "com.mojang.blaze3d.platform.TextureUtil"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 13 more
```
The solution was to overwrite all 3 classes from the package.

**Comment by peterix** [comment]
I mean, even with vanilla, this doesn't work for me.

If I manually put in the version and the OF jar, I get the same-ish problem. A GL context related crash in a random thread. Likely whatever function ends up running into a GL call first.

I can see the patches in the OF jar, I assume they are being applied correctly at runtime.

**Comment by sp614x** [comment]
The GL initialization is started by the patch of `com.mojang.blaze3d.platform.GLX`.
If the patch is not applied the GL initialization happens on a random thread later and crashes.
Combined with the security exception above, it looks like the Launchwrapper has problems when patching classes not in the default package. It is probably not removing the package signer information.
Up to 1.13 OF was only patching classes that were in the default package.

**Comment by peterix** [comment]
Well, looks like launchwrapper is the thing to investigate then... Maybe add extra logging to see what's being loaded and how. I might poke at this over the weekend unless I'm busy with something else.

**Comment by sp614x** [comment]
Probably this line: https://github.com/Mojang/LegacyLauncher/blob/master/src/main/java/net/minecraft/launchwrapper/LaunchClassLoader.java#L138
It skips class signing only for default package and `net.minecraft.*` classes.

**Comment by TheMCNerd2017** [comment]
Has anyone found a solution to this? I just updated to 1.14.2 and am having the same exact issue.

**Comment by xAphex** [comment]
@TheMCNerd2017 https://github.com/MMCInstances/OptifineInstances

**Comment by TheMCNerd2017** [comment]
> @TheMCNerd2017 https://github.com/MMCInstances/OptifineInstances

Thank you so much, the JAR file from that repository was all I needed to fix the issue (not sure how though). I guess the JAR file from the official Optifine site is broken, and the one from there is fixed?

**Comment by xAphex** [comment]
> 
> 
> > @TheMCNerd2017 https://github.com/MMCInstances/OptifineInstances
> 
> Thank you so much, the JAR file from that repository was all I needed to fix the issue (not sure how though). I guess the JAR file from the official Optifine site is broken, and the one from there is fixed?

the jar from that repository is extracted version of the official jar

**Comment by sp614x** [comment]
@peterix is this version working better?
https://optifine.net/tmp/OptiFine_1.14.3_HD_U_F1_pre16_Launcher.jar

It uses a modified launchwrapper that allows the patching of "com.mojang.blaze3d".

**Comment by xAphex** [comment]
@sp614x https://paste.ee/p/p8dpD
same issue persists on the file u uploaded above.

**Comment by sp614x** [comment]
```
C:/Users/Gabi/Desktop/MultiMC/instances/1.14/libraries/launchwrapper-2.0.jar
```
The used launchwrapper is the problem.

The above OF jar contains a "launchwrapper-2.0.jar" which is updated to allow patching of the package "com.mojang.blaze3d".

This line has to be fixed by adding the same check for "com.mojang.blaze3d" as there is for "net.minecraft":
https://github.com/Mojang/LegacyLauncher/blob/master/src/main/java/net/minecraft/launchwrapper/LaunchClassLoader.java#L138

**Comment by xAphex** [comment]
**Solution:**

Move OptiFine above LWJGL in MultiMC:
![image](https://user-images.githubusercontent.com/5391237/60287558-d7c93d00-991a-11e9-9909-4a13fcdcd839.png)

**Comment by zacharee** [comment]
> @peterix is this version working better?
> https://optifine.net/tmp/OptiFine_1.14.3_HD_U_F1_pre16_Launcher.jar
> 
> It uses a modified launchwrapper that allows the patching of "com.mojang.blaze3d".

Extracting this, then using the launchwrapper JAR from it alongside the current version of the OptiFine_MOD JAR works for me with MultiMC.

**Comment by peterix** [comment]
That maybe launches, but it also doesn't do anything.

**Comment by peterix** [comment]
@xAphex if you move OptiFine above everything else, it will not work at all - you are launching vanilla at that point. So, it runs, but it doesn't do anything.

**Comment by peterix** [comment]
@zacharee extracting entirely invalidates this whole thing.

**Comment by peterix** [comment]
So, testing wirth this:
[OF 1.14.3.zip](https://github.com/sp614x/optifine/files/3337523/OF.1.14.3.zip)

I get logs like this one:
https://paste.ee/p/p8BZh

It seems that whatever the installer is doing is not happening when using the tweaker.
Or it is a separate issue.

**Comment by zacharee** [comment]
> @zacharee extracting entirely invalidates this whole thing.


Simply extracting the latest OF version for 1.14.3 doesn't work. It hits the blaze3d signature error. It worked on 1.14.2, but 1.14.3 needs both the extracted mod and the patched launchwrapper.

**Comment by douglasrizzo** [comment]
I was able to make "1.14.4 HD U F2" work in MultiMC by loading it as a Fabric mod. I installed Fabric through the MultiMC GUI button "Install Fabric", then I downloaded the [OptiFabric](https://www.curseforge.com/minecraft/mc-mods/optifabric) and OptiFine 1.14.4 HD U F2 jar files and added them as mods in the "Loader Mods" tab of my MultiMC instance window.

All of this loaded both Fabric and OptiFine in Minecraft 1.14.4 without any issues.

**Comment by ZekerZhayard** [comment]
@sp614x  I think it is an issue about `optifine.OptiFineClassTransformer`.  

In `OptiFineClassTransformer#getOptiFineResource(String)`, the value of the parameter `name` is the full class name split with "." (e.g. `com.mojang.blaze3d.platform.GLX.class`), but the correct name should be `com/mojang/blaze3d/platform/GLX.class`.  
Therefore, `OptiFineClassTransformer#tramsform(String, String, byte[])` should add some codes like below:
```java
public byte[] transform(final String name, final String transformedName, final byte[] bytes) {
    if (name.startsWith("com.mojang.blaze3d.")) {
        name = name.replace(".", "/");
    }
    // ...
}
```

**Comment by ZekerZhayard** [comment]
this issue may have been fixed in 1.17.1 H1 pre2

**Comment by sp614x** [comment]
The original issue was fixed for 1.14.4.

**Comment by ZekerZhayard** [comment]
> The original issue was fixed for 1.14.4.

no, this issue still exists under 1.17.1_G9 for the OptiFine **without extracting**:
log: https://paste.ee/p/FNlX3
MultiMC profile: https://paste.ee/p/oHkPa

**Comment by phit** [comment]
seems to be fixed in 1.18 pre4 and launchwrapper 2.3, thanks for the profile @ZekerZhayard
