### ISSUE TITLE
[1.15.2] Emissive Textures not working

### ISSUE THREAD

**Issue by obonilla87** [sp614x/optifine#3437]
Emissive textures for blocks, items, and entities (including mobs) weren’t loaded in 1.15.2 when using a resource pack with Optifine 1.15.2 Pre9.

Examples included:
witch_emissive.png for witch.png
redstone_ore_emissive.png for redstone_ore.png
torch_emissive.png for torch.png

**Comment by JerryWester** [comment]
Does `<resource pack root>/assets/minecraft/optifine/emissive.properties` exist?
If so, does it include the line `suffix.emissive=_emissive`?

**Comment by obonilla87** [comment]
It does have it.

**Comment by Zefferis** [comment]
I'm having the same issue with Pre13

minecraft/optifine
``emissive.properties``

> ``suffix.emissive=_e``

Doesn't appear to do anything in-game

**Comment by Ratchet97** [comment]
Still a bug in pre 19.

**Comment by Demirath** [comment]
Still a bug in pre20.

**Comment by Ratchet97** [comment]
Still a bug in pre21.

**Comment by HyPeRXKo** [comment]
Still a bug in pre22.

**Comment by Ratchet97** [comment]
Still a bug in pre23.

**Comment by DieselDorky16** [comment]
Can somebody please fix this bug for the next pre-release for goodness sake?

**Comment by Demirath** [comment]
You need to be patient, my dude. I'm looking forward to emissive textures too, but bugging the dev won't make things go faster. There's exactly one person writing this whole thing, by themselves, practically from scratch. 
They closed all the other emissive texture issues 10 days ago, so presumably it's on their radar and they'll get to it when they get to it.

**Comment by Rygi3l** [comment]
Still a bug in pre24.

**Comment by HyPeRXKo** [comment]
i really hope this is fixed in pre26 or pre27 👍

**Comment by sp614x** [comment]
Fixed in pre25.

**Comment by pointydev** [comment]
Still not working for blocks on my end, only while handheld:
![](https://pointy.needs-to-s.top/9mcQNxS.png)

**Comment by Demirath** [comment]
![2020-06-14_14 54 07](https://user-images.githubusercontent.com/25912441/84603204-233d6980-ae52-11ea-9127-e34b22b0d575.png)
That's weird, it's been working for me so far

**Comment by pointydev** [comment]
Alright found out that having smooth lighting turned completely off was preventing emissives from working. Fixed(?).
