### ISSUE TITLE
Enchanted Items in Fast Render

### ISSUE THREAD

**Issue by motangish** [sp614x/optifine#409]
if fast render is enabled then enchanted items don't will displayed correctly.
Link to image: http://imgur.com/a/1ESxN
OptiFine 1.7.10 HD U D6

**Comment by sp614x** [comment]
It looks like this bug was fixed in OptiFine 1.8.8_HD_U_F2, but the fix was not backported to 1.7.10.

**Comment by ZephaniahNoah** [comment]
Actually this still happens in Optifine 1.11.2 HD_U_B5
https://s24.postimg.org/4fqba9azp/2017_01_05_11_18_09.png

**Comment by sp614x** [comment]
Fixed in OptiFine 1.11.2_HD_U_B8

**Comment by sp614x** [comment]
To be fixed in 1.7.x and 1.8.x.
