### ISSUE TITLE
[Bug] 1.16 Hostile mobs appearing invisible and invulnerable.

### ISSUE THREAD

**Issue by PapaCheerio** [sp614x/optifine#4351]
## Description of Issue
   While running OptiFine, with or without shaders Hostile Mobs can become invisible and invulnerable.

## Steps to Reproduce
   I was running OptiFine while playing on a Realm both with and without shaders. I have yet to experience this while playing on a Local world but after a very brief amount of time hostile mobs would begin to appear invisible while still audible and able to harm the player but unable to be harmed.
   This also occurred whether custom entity models were enable or not.

## OptiFine Version
   OptiFine 1.16.1 HD U G2 pre4

## Installation Method
   I used the Installer.

## Other Installed Mods
   Vanilla

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
  No this does not occur in Vanilla without optifine.

## Additional Information
4:30 minute video showing an example of the bug.
https://streamable.com/s9y2js

**Comment by Regnander** [comment]
Related #4322

**Comment by sp614x** [comment]
Seems to be fixed with 1.16.2 pre6.

**Comment by ituitis20-ugurh20** [comment]
> Seems to be fixed with 1.16.2 pre6.

Nothing is fixed. Mobs are being STILL invisible and invincible yet they still are able to damage the player in 1.16.3. It literally makes it unusable. Please actually fix it so that we can use it. It's such a contentful addition to the game.

**Comment by dabulue** [comment]
> Seems to be fixed with 1.16.2 pre6.

Nothing is fixed. Mobs are being STILL invisible and invincible yet they still are able to damage the player in 1.16.3. It literally makes it unusable. Please actually fix it so that we can use it. It's such a contentful addition to the game.

**Comment by Lythael** [comment]
> > Seems to be fixed with 1.16.2 pre6.
> 
> Nothing is fixed. Mobs are being STILL invisible and invincible yet they still are able to damage the player in 1.16.3. It literally makes it unusable. Please actually fix it so that we can use it. It's such a contentful addition to the game.

Can confirm this still happens in 1.16.4 release aswell.
Mobs noticed going invisbile so far : Piglins (near Bastion) , Skeletons (Overworld)

**Comment by ituitis20-ugurh20** [comment]
Exactly. Yet they still close this issue. It also has this problem with the HunterIllager mod's mob.
