### ISSUE TITLE
Invisible enemies. Optifine 1.16.1 pre4-pre9

### ISSUE THREAD

**Issue by Roy1232** [sp614x/optifine#4465]
## Description of Issue:
Many times it has happened to me that suddenly something is hurting me but there is absolutely nothing around, but if I close and open the world again I realize that I have a mob hitting me.

## Steps to Reproduce
Normally I think it happens when loading chunks, and some entities don't render correctly, this is a guess.

## OptiFine Version
It takes me through from 1.16.1 pre4 to 1.16.1 pre9

## Installation Method
Directly download optifine from the official website and install it as a .jar.

## Log Files/Crash Reports
I have never crashed the game with this bug.

## F3 Debug Screenshot
![2020-07-25_19 57 36](https://user-images.githubusercontent.com/68801692/88472378-27908400-cee0-11ea-98b0-c3a1f1796415.png)
![2020-07-25_19 58 00](https://user-images.githubusercontent.com/68801692/88472382-2e1efb80-cee0-11ea-8e18-443a25c2443c.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
Nope, it never happened in Vanilla.

## Additional Information
I don't play with mods, so I can't provide that info, but this is not 100% sure but I would swear that once this invisible mob was hitting me I couldn't hit the mob (and hit 360 degrees) until I relogged on my world and there if I could hit him.

**Comment by emaraldsoup** [comment]
do you experience this bug in optifine 1.16.1 pre10?

**Comment by Roy1232** [comment]
Nope, I will install the pre 10 now, and I will tell you in the following days if I have continued to experience it! ^ - ^

**Comment by sp614x** [comment]
Should be fixed.

**Comment by thyIacoIeo** [comment]
Still experiencing this issue in _OptiFine 1.16.1 HD U G2_ with nametagged hostile mobs

Steps to reproduce: spawn hostile mob and give nametag. Repeatedly leave and return to render distance. Sometimes the hostile mobs will be rendered when you come back; sometimes they won't. Mobs which are invisible appear to have no collision(no hitbox appears with f3+B) but can still attack.
