### ISSUE TITLE
[Bug] OptiFine 1.8.9 L5 has white screen on macOS Big Sur

### ISSUE THREAD

**Issue by charboo2** [sp614x/optifine#5028]
## Description of Issue
When using OptiFine L5 or L6 and opening Minecraft on macOS Big Sur, the game window is white. The game still works, there are just no textures so everything is all white.

## Steps to Reproduce
1. Launch Minecraft with OptiFine on macOS Big Sur. (I only tested 1.8.9 L5 and L6)
2. The window is just white.

## OptiFine Version
1.8.9 L5 and L6 preview

## Installation Method
I downloaded OptiFine from the official website and installed as standalone.

## Log Files/Crash Reports
https://pastebin.com/hGn7dzzY

## F3 Debug Screenshot
I can't take an F3 screenshot

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
No.

## Additional Information

N/A

**Comment by 2LO7** [comment]
Yes, same problem here, macOS Big Sur doesn't let fullscreen optifine, basically all versions. It's quite frustrating.

**Comment by scotow** [comment]
I got a related issue on Big Sur using Optifine 1.8.9 L5 and MultiMC. The Minecraft client crashed after a second with the following stack trace. Hope it helps:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff204986af __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff201d03c9 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff204c0a9a -[NSException raise] + 9
	3   AppKit                              0x00007fff22c6097d -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 321
	4   AppKit                              0x00007fff22c88cf3 -[NSThemeFrame setStyleMask:] + 142
	5   AppKit                              0x00007fff22c88a89 __25-[NSWindow setStyleMask:]_block_invoke + 2057
	6   AppKit                              0x00007fff22c88226 NSPerformVisuallyAtomicChange + 132
	7   AppKit                              0x00007fff22c8812f -[NSWindow setStyleMask:] + 170
	8   liblwjgl.dylib                      0x0000000158f0acca Java_org_lwjgl_opengl_MacOSXDisplay_nSetResizable + 90
	9   ???                                 0x000000010bc67407 0x0 + 4492522503
	10  ???                                 0x000000010bc56ffd 0x0 + 4492455933
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by MemeMasterOJ** [comment]
Seems to work for me on 1.16.4 but not 1.8

**Comment by 2LO7** [comment]
Yeah I really wish someone would fix this.

**Comment by IMS212** [comment]
ok, for anyone affected by this try installing and selecting the [corretto jdk ](https://corretto.aws/downloads/latest/amazon-corretto-8-x64-macos-jdk.pkg) to use in something like multimc or vanilla launcher and try again.

**Comment by scotow** [comment]
> ok, for anyone affected by this try installing and selecting the [corretto jdk ](https://corretto.aws/downloads/latest/amazon-corretto-8-x64-macos-jdk.pkg) to use in something like multimc or vanilla launcher and try again. (EDIT: This seems to fix the crash mentioned by @scotow but not the white screen of OP.)

Indeed. Thank you for the fix.

**Comment by sp614x** [comment]
Relevant #5034

**Comment by charboo2** [comment]
The new preview versions still do not fix this issue on Mac, and it is unclear if the problem is being worked on or not.

**Comment by DieselDorky16** [comment]
This bug is affecting 1.8.9 M5. Admins fix this.

**Comment by MisterCheezeCake** [comment]
This bug has been reported for more than 90 days and yet nothing has been done. This is honestly shameful as it literally prevents a moderate portion of the userbase from using the mod and for some, by extension playing the game.

**Comment by DieselDorky16** [comment]
When will this bug be fixed on ALL versions of Optifine?

**Comment by DieselDorky16** [comment]
Any chance the bug could be caused by this: `The jar file /Users/<user>/Library/Application Support/minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.jar has a security seal for path org.lwjgl.opengl, but that path is defined and not secure`

**Comment by xeisch** [comment]
there is unfortunately no fix for this, however full screen with optifine works on 1.16+. If you are using optifine to change the resolution you play with for more fps, try quickres or any other programs that change the resolution of the screen itself, not the game. If you load minecraft without optifine and untick fullscreen and load back with optifine, there wont be white screen, then just click green exand button on the minecraft window itself to make the window fullscreen. Also try changing lauch resolution settings in the launcher. Currently this is the only fix for this. As 1.8+ minecraft is outdated, i doubt they will do something about this bug. Next step is just wait for any new Big sur updates...
Hope this helps

**Comment by charboo2** [comment]
I don’t believe you. sp614x has acknowledged this issue and there has been no word about whether a fix is possible or not. All of us are simply biding our time and hoping this issue comes to the top of sp614x’s list. How do you know there is no fix?

**Comment by xeisch** [comment]
> I don’t believe you. sp614x has acknowledged this issue and there has been no word about whether a fix is possible or not. All of us are simply biding our time and hoping this issue comes to the top of sp614x’s list. How do you know there is no fix?

There is no fix for this problem at the moment. What this means is simply rn there is no fix that we can use, like playing with ingame settings or using other mods etc. I am too hoping that sp614x will do something with it, but as i said, 1.8.9 is outdated, although most large servers are hosted on this version. This bug is also present on all versions from 1.8 throughout 1.15, in addition not many people play mc on a mac, instead use bootcamp thus fixing this bug wont be a priority for the devs. I’ve got m1 mac book pro and cant use bootcamp, lets just wait either for WWDC where apple announces licensing of windows 10 for ARM, update to big sur or 1.8.9 optifine fix. 🤞

**Comment by scotow** [comment]
@xeisch Did you encounter any issue playing MC on a M1 Mac (beside the bug this issue relates to)? I'm curious.

I know it's not the fix you people are waiting for, but @IMS212 's fix is pretty convenient. Just install the AWS modified version of the JRE and it will fix the Optifine bug. Once installed, it's pretty seamless and you don't have to worry with in-game settings or mods anymore.

**Comment by xeisch** [comment]
> @xeisch Did you encounter any issue playing MC on a M1 Mac (beside the bug this issue relates to)? I'm curious.

Held my fingers crossed in hope that your advice with coretto 8 will help, unfortunately it doesnt fix the white screen. Besides the issue this thread is assigned to, i am playing on m1 pro with: max resolution, full screen, VBO on, vsync off, with NEU and Pather mods on hypixel skyblock, no optifine and getting stable 200fps, rarely drops to less than 60 but thats just coz my wifi is 1.5mb/s.
To answer your question on any issues other than optifine, i still do get white screen when loading into mc, however i delete modcore folder that comes with Patcher mod so that the game installs it again and it seems to fix it. If anyone is getting white screen regardless wether you have optifine or not, load vanilla mc and turn off full screen in settings, reload back to forge, expand screen to fullscreen (green button on the window it self) and then turn on fullscreen in mc settings.

**Comment by DieselDorky16** [comment]
WHY IS IT NOT FIXED?

**Comment by Milo123459** [comment]
> WHY IS IT NOT FIXED?

Take a minute to think about that. There is 1 talented dev working on a massive project, it's not opensource for legal reasons. Calm down. Try some of the fixes stated above. Open source should not be toxic.

**Comment by sp614x** [comment]
Looks like the fix for #4824 also fixes the white screen on Big Sur.
The bugfix is in available in M6_pre1 for 1.8.9.
Please check if working properly.

**Comment by ZenIsBestWolf** [comment]
Working MBP Mid 2014 (Intel)

**Comment by charboo2** [comment]
The bug fixed for me with the new prerelease. Thank you so much for fixing this bug, it’s plagued me and many others for 150+ days!

**Comment by Jakubk15** [comment]
Still not fixed :/

**Comment by Feel65** [comment]
I still encounter this issue daily.

**Comment by eqixcx** [comment]
> I still encounter this issue daily.

using the coretto jdk worked for me :p  [coretto jdk](https://corretto.aws/downloads/latest/amazon-corretto-8-x64-macos-jdk.pkg)

**Comment by Feel65** [comment]
> > I still encounter this issue daily.
> 
> using the coretto jdk worked for me :p [coretto jdk](https://corretto.aws/downloads/latest/amazon-corretto-8-x64-macos-jdk.pkg)

thanks so much! I still get occasional JVM crashes but now I can see!

**Comment by ddozzi** [comment]
if you're still encountering the crash, even after using the corretto jdk, try downloading an older build from their github. [this](https://github.com/corretto/corretto-8/releases/tag/8.292.10.1) one worked for me.

**Comment by Feel65** [comment]
Cool, thanks! Suprisingly enough, Sk1er’s new Essentials/ModCore2.0 in
patcher 1.6 seems to have greatly lowered the crash rate, although I don’t
know why

**Comment by Jackli2009** [comment]
[minecraft-exported-logs-2021-08-24T15-33-13.log](https://github.com/sp614x/optifine/files/7037407/minecraft-exported-logs-2021-08-24T15-33-13.log)
it is terrible!

**Comment by Feel65** [comment]
Cry about essential all you want, it’s great

**Comment by Jay59376** [comment]
works for me

**Comment by DieselDorky16** [comment]
When will this issue be fully fixed? It said it's patched, but it's clearly not (using latest preview of 1.8.9)

**Comment by Jay59376** [comment]
> Late reply but I'd recommend using Lunar Client because they have the bug patched, although it will white screen every 4 or 5 fullscreens but relaunching ur game will fix it.

but what if your a cracked player : / , you cant use lunar.

**Comment by DieselDorky16** [comment]
This is still an issue on 1.12.2

**Comment by Feel65** [comment]
then you can't use optifine either

**Comment by DieselDorky16** [comment]
This bug has made a return, and it's worse.

**Comment by christopherlewisghs** [comment]
Seriously, how long has it been? The issue, is back. Yet again. On macOS 13.

**Comment by charboo2** [comment]
Open your own support ticket then. This is concerning 1.8.9 not 1.12. The original issue has been solved so please do not keep reviving this thread.

**Comment by FLODJES** [comment]
I'm still having this problem. Every time I try to go in fullscreen my game crashes.
MacOS 11.7 (Big Sur), Optifine 1.8.9

**Comment by Grify** [comment]
Same whitescreen, crash on 1.8.9 M6 pre2 on ventura

**Comment by SashaSemenishchev** [comment]
Yep happens sometimes on M5, ventura. Sometimes crash, sometimes white screen. BTW If you have other physical monitor attached, and you drag the window there, it will fix the white screen and you can drag the window back.

**Comment by ironboy36** [comment]
macOS Big Sur 11.7.4, issue still hasn't got fixed, does anyone even have JVM Arguments that can support this gray screen issue, also on older versions of Minecraft (including 1.12.2) down to Minecraft Classic, this issue occurs on ALL OF IT!

**Comment by Feel65** [comment]
still happening for meSent from my iPhoneOn Jun 3, 2023, at 11:58 AM, ironboy36 ***@***.***> wrote:﻿
macOS Big Sur 11.7.4, issue still hasn't got fixed, does anyone even have JVM Arguments that can support this gray screen issue, also on older versions of Minecraft (including 1.12.2) down to Minecraft Classic, this issue occurs on ALL OF IT!
