### ISSUE TITLE
[1.8.x] Optfine's fullscreen not working in Mac's New Update (Big Sur)

### ISSUE THREAD

**Issue by c0wling** [sp614x/optifine#5034]
<img width="854" alt="Screen Shot 2020-11-15 at 1 25 15 pm" src="https://user-images.githubusercontent.com/74478364/99161768-9290ef80-2749-11eb-9d02-691f4aaa0a66.png">

When going into fullscreen on Optifine (this doesn't happen in vanilla Minecraft) it will give you a completely blank white screen (Not Mac's native fullscreen setting, Optifine's fullscreen. Accessible by going to Settings > Video > Other > Fullscreen.) Although it is still playable without using Optfine's fullscreen I get worse fps and since I use a different resolution my GUI scale is messed up. As far as I know this bug effects 1.7 - 1.8 Optifine. It may affect other versions but I have not tested it. Before the Big Sur update on Mac, it would work perfectly fine.

To get to this bug you have to be on Mac (I assume it doesn't affect windows, but I don't know) and go into Optifine fullscreen. By going to Settings > Video > Other > Fullscreen.

The versions I've tried are 1.7 and 1.8, but it most likely affects other versions.

I've used it with Lunar Client (which has Optifine preinstalled), Badlion Client (which has Optifine preinstalled), and on the default Minecraft launcher. It is preinstalled on Lunar Client and Badlion Client and on the default Minecraft launcher I put Optifine 1.8 L5 in the mods folder.

I used the forge version.

The only mods I used were Lunar Client and Badlion Client. And when I used it on the default Minecraft there were no other mods.

The game did not crash it just would stay on the white screen forever until I closed it.

I can not get on the debug menu.

It doesn't happen in vanilla Minecraft. It made no difference if I used mods (I only used Lunar Client and Badlion Client) Since Fabric is not available in 1.7 or 1.8 I do not know if it still happens on Fabric. But I assume it does because this doesn't happen on vanilla which makes it seem like it is something in Optifine.

**Comment by MemeMasterOJ** [comment]
having the same issue

**Comment by c0wling** [comment]
At least I'm not alone on this issue.

**Comment by TrueKevinGamer** [comment]
same

**Comment by IMS212** [comment]
This happens in fabric (i have tried with a fork of optifabric for 1.8)

**Comment by c0wling** [comment]
damn

**Comment by dhorne55** [comment]
This is not a true fix, but you can at least go back to playing in window mode if you edit the fullscreen to false in options.txt in the instance directory.

**Comment by c0wling** [comment]
An easier fix is to launch vanilla Minecraft go out of fullscreen mode (it works in vanilla) and launch Minecraft with Optifine with the unfullscreened Minecraft tab in the background. You can close it after

**Comment by galacticrepublic1** [comment]
I have the same issue on the new M1 Mac see #5117

**Comment by c0wling** [comment]
Anyone have help for Lunar Client (a modpack with Optifine preinstalled) when I use it, it automatically gives me the white screen. I have used the previous methods above (the one I posted and the one @dhorne55 posted) but neither have worked. Help would be appreciated.

**Comment by TrueKevinG** [comment]
I think I fix it but reinstalling lunar client or badlion client

**Comment by c0wling** [comment]
I have already tried reinstalling. I even used Appcleaner but it would still go to the white screen.

**Comment by c0wling** [comment]
I fixed it, instead of uninstalling Lunar Client I instead uninstalled Minecraft and all its related files (I recommend using AppCleaner) and I launched Lunar Client again and it didn't go into the white screen. Tip: Save your texture packs and Optifine settings because they won't be saved.

**Comment by PeterQueen** [comment]
Ok, after after I managed to fix this bug. I am really upset tho. It should work if you go on minecraft vanilla and then toggle off the fullscreen mode in the settings. Then you only have to manually enter the fullscreen mode (by clicking the green circle) every time you launch minecraft, but I don't think it's a so big of a deal. IF IT STILL DOESN'T WORK: try to go to the minecraft launcher, then go to the "installations" window and edit the resolution (you can put what you want, try for example 1920x1080). If it still doesn't work try to launch minecraft vanilla (not in fullscreen mode) and then while it is open launch also at the same time the optifine (to keep the minecraft launcher open while minecraft is running you have to go on the minecraft launcher settings). This bug could be easily fixed by changing the code of something but I honestly know nothing about that stuff, so yeah... Hope this will help you.

**Comment by PeterQueen** [comment]
Ok nvm the things that I said earlier only works with optifine. For example I tried to open lunar client and it still shows me up the white screen. I'm trying to solve this problem. This is so annoooooooying

**Comment by Cart3r1234** [comment]
Lunar and other pvp clients tend to cause a lot of issues anyway, so problems cause by combinations of non-vanilla clients + optifine usually are not given any support.

**Comment by PeterQueen** [comment]
Ok I'm so proud of myself I think i solved this problem xD. To change the settings of lunar client without opening lunar client you have to go: library > application support > minecraft > optionsLC.txt  Then you only have to edit the file by setting the fullscreen mode to "off". I just don't get how and where the files are saved on mac, it doesn't make any sense to me. It should work for everyone, hope you'll find it useful, it took me a lot of time u___u

**Comment by ODDFTW** [comment]
Wait what do you mean by the library? I am having this same issue where I was changing my setting and accidentally clicked on, On for fullscreen then it ruined everything. I am very upset and don't know how to fix this. somebody pls help.

**Comment by ODDFTW** [comment]
@PeterQueen I tried doing what you said and it did fix it form going into fullscreen but it still is a white screen.

**Comment by PeterQueen** [comment]
hmmmmm, it should work tho. Try to double check the file another time, are you sure it is "optionsLC.txt", and not "options.txt"? I suggest you also to fix this last file btw, because it makes changes on the optifine. Or maybe you just didn't save xD, simply type cmd+s

**Comment by Sreerahul123** [comment]
@PeterQueen im not quite sure what u mean by 'Library', sorry if i'm being a pain in the neck ;( i am running macOS Big Sur and I have the same white screen issue

**Comment by Sreerahul123** [comment]
although there is a folder named 'Libraries', but it has no 'optionsLC.txt' when I click on it.
<img width="1055" alt="Screenshot 2020-12-27 at 11 22 30" src="https://user-images.githubusercontent.com/69305178/103169678-d5101680-4835-11eb-893e-dc15a6d3f68e.png">
<img width="1060" alt="Screenshot 2020-12-27 at 11 22 15" src="https://user-images.githubusercontent.com/69305178/103169681-da6d6100-4835-11eb-930a-01df7a1b6be5.png">

**Comment by Sreerahul123** [comment]
OMG it works, all u have to do is chang the resolution in the Lunar Client app, I have it set as 1980x1080, I launched 1.8 and it is running now.

**Comment by PeterQueen** [comment]
Ok I hope it works for everyone, there are different methods and I don't even know if all your files are saved in the same place of mine...

**Comment by c0wling** [comment]
@Sreerahul123 it dosent work xD i use switchresx now

**Comment by ZenIsBestWolf** [comment]
#5028 is being dedicated as the main issue for this.

**Comment by DieselDorky16** [comment]
WHY IS IT NOT FIXED?

**Comment by PeterQueen** [comment]
> WHY IS IT NOT FIXED?

Lol I installed bootcamp, but on mac it still works

**Comment by Milo123459** [comment]
> WHY IS IT NOT FIXED?

Take a minute to think about that. There is 1 talented dev working on a massive project, it's not opensource for legal reasons. Calm down. Try some of the fixes stated above. Open source should not be toxic.

Oh, and, stop posting the same thing on multiple issues. It's annoying, please learn some basic manners before screaming at people.

**Comment by ZenIsBestWolf** [comment]
Please dedicate all discussion of this issue to #5028
