### ISSUE TITLE
[Texture Bug] Item frames and banners have bad textures with anisotropic filtering turned on (1.16.4_HD_U_G6_pre4)

### ISSUE THREAD

**Issue by Eraene** [sp614x/optifine#5159]
## Description of Issue
Placed item frames and banners have erroneous textures with anisotropic filtering turned on.
https://i.imgur.com/mcyTiAE.gif

## Steps to Reproduce
1. Turned on anisotropic filtering.
2. Nothing else. That was it. 

## OptiFine Version
1.16.4_HD_U_G6_pre4

## Installation Method
How did you install OptiFine? Did you use the included standalone installer, or did you drop the JAR file into your "mods" folder?
Installed via opening JAR.

## Other Installed Mods
- Using no other mods.

## F3 Debug Screenshot
![image](https://user-images.githubusercontent.com/29924875/103325089-ca10de00-4a0f-11eb-8996-5133d4982424.png)

## Prior Testing
If you've installed standalone:
- Does this happen in Vanilla without OptiFine?
- This does not happen with anisotropic filtering turned off. Vanilla does not apply.

**Comment by sp614x** [comment]
Fixed in pre5.

**Comment by SlimeDog** [comment]
This issue is not completely fixed in G6-pre5. I'm still seeing glitched banners. The vanilla client rendering is correct.

**Comment by Cart3r1234** [comment]
I can also confirm that in pre5 this is still an issue with banners.  The banners will load in correctly on the first load, but upon unloading and reloading the chunk, they start to flash

**Comment by SlimeDog** [comment]
All better with G6-pre6. Thank you.
