### ISSUE TITLE
Shaders do not render correctly at all with OptiFine 1.16.5_HD_U_G8_pre3 and above

### ISSUE THREAD

**Issue by giorov** [sp614x/optifine#5433]
Shaders do not render correctly with OptiFine 1.16.5_HD_U_G8_pre3 and pre4 (unplayable).

I use DePixel textures

I assume it has to do with the lazy chunk loading input lag fix or the previous implementation on the changelog.

Running correct Forge version, as usual, and client 1.16.5

I'm on a Radeon Vega 56, latest drivers.

This is with BSL shader on:
![2021-03-10_20 27 39](https://user-images.githubusercontent.com/37343119/110736558-b8eb0700-81e0-11eb-83bd-d1d2a72871d9.png)

This is with internal shader on:
![2021-03-10_20 28 28](https://user-images.githubusercontent.com/37343119/110736565-bc7e8e00-81e0-11eb-8b1a-f6ca92c93e18.png)

**Comment by NovaN4** [comment]
Can confirm, I have this issue too; had to downgrade to G8_Pre2

**Comment by Sudo-Stefano** [comment]
Same issue, on vanilla and modded version.

**Comment by sp614x** [comment]
Fixed, coming in pre5.

**Comment by jinkhya** [comment]
Hello it's a lot better but it looks like it still doesn't like refined storage : https://i.imgur.com/bfPcuIs.png

**Comment by sp614x** [comment]
Refined storage crashes for me:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 6
	at net.minecraftforge.client.model.pipeline.BakedQuadBuilder.put(BakedQuadBuilder.java:99) ~[?:?] {re:classloading}
	at net.minecraftforge.client.model.pipeline.VertexTransformer.put(VertexTransformer.java:68) ~[?:?] {re:classloading}
	at net.minecraftforge.client.model.pipeline.TRSRTransformer.put(TRSRTransformer.java:57) ~[?:?] {re:classloading}
	at net.minecraftforge.client.model.pipeline.LightUtil.putBakedQuad(LightUtil.java:110) ~[?:?] {re:classloading}
```
If other mods work correctly, then it may be something in the RefinedStorage models.

**Comment by jinkhya** [comment]
Wait really?
I'm running RS 1.9.12, optifine G8 pre5 and forge 36.0.46.

**Comment by sp614x** [comment]
OptiFine is compatible with Forge 36.0.42. 
There could be some difference to .46.
