### ISSUE TITLE
[1.17] Entity shadows not working with shaders

### ISSUE THREAD

**Issue by mapleSyrup982** [sp614x/optifine#5883]
## Description of Issue
when i play on optifine 1.17 and run shaders I cannot see entity shadows, idk why this happens

## OptiFine Version
1.17-OptiFine_HD_U_G9_pre22

## Installation Method
standalone installer

## F3 Debug Screenshot

![2021-06-26_11 16 51](https://user-images.githubusercontent.com/86534266/123523818-4cfbb400-d694-11eb-9455-533faaecabfd.png)
![2021-06-26_15 29 02](https://user-images.githubusercontent.com/86534266/123523827-600e8400-d694-11eb-9def-c6e2ff3a2bb0.png)

## Prior Testing
- Does this happen in Vanilla without OptiFine?
no

## Additional Information
this happens on all shaders

**Comment by KaiAF** [comment]
Fixed in latest pre version

**Comment by mapleSyrup982** [comment]
this is still a problem in pre23;
![2021-06-27_12 15 14](https://user-images.githubusercontent.com/86534266/123552151-d8338300-d742-11eb-9aa6-8ceaff77365b.png)
![2021-06-27_12 15 31](https://user-images.githubusercontent.com/86534266/123552163-dec1fa80-d742-11eb-8973-6d1c24aa243f.png)

**Comment by Whitelisted1** [comment]
Are entity shadows on? You might have turned them off, or maybe your specific shader pack doesn't support entity shadows

**Comment by mapleSyrup982** [comment]
I definitly have entity shadows on (the button in the same menu as view bobbing)

**Comment by Whitelisted1** [comment]
Try another shader pack and see if it works

**Comment by mapleSyrup982** [comment]
this is also a bug in seus renewed

**Comment by sp614x** [comment]
Fixed, coming in next preview
