### ISSUE TITLE
Lightning issues with shaders 

### ISSUE THREAD

**Issue by HZR-Kairos2** [sp614x/optifine#5895]
## Description of Issue
attempting to use both sildurs high and seus renewed result in strange bugs. In sildurs it seems lights dont work entirely and chests are highlighted. With seus it light seems to working however only close to you and chests seem to have no light on them. there is also the issue of particles appearing though walls and not connected to the their respective items

## Steps to Reproduce
I am running fabric with the mod optifabric which may be the cause of some issues. However other than that they are all the default settings. I just click on the shader like anyone would 

## OptiFine Version
1.17 G9 pre22

## Installation Method
I have fabric installed so i just dragged and dropped it into the mods folder and I am using it in conjunction with the mod optifabric

## Fabric/Forge Version
fabric-api-0.35.1
fabric 0.7.4

## OptiFabric Version
optifabric 1.11v

## Other Installed Mods
mod menu 2.0.2
Xaeros minimao 21.12.2
easier chest 0.32.9

![2021-06-27_08 54 25](https://user-images.githubusercontent.com/86549718/123537463-83364380-d727-11eb-9e13-49d898cb1c8d.png)
![2021-06-27_08 54 30](https://user-images.githubusercontent.com/86549718/123537466-84677080-d727-11eb-87e9-1413bb2a5ede.png)
![2021-06-27_08 53 54](https://user-images.githubusercontent.com/86549718/123537467-85000700-d727-11eb-8ef1-398ae8a7937c.png)
![2021-06-27_08 54 03](https://user-images.githubusercontent.com/86549718/123537468-85989d80-d727-11eb-8519-acb923a600f3.png)
![2021-06-27_08 54 21](https://user-images.githubusercontent.com/86549718/123537470-86c9ca80-d727-11eb-9c1b-a3124787de2f.png)

**Comment by OblivionFall** [comment]
![2021-06-27_10 04 16](https://user-images.githubusercontent.com/86563416/123549603-630a8280-d72f-11eb-836c-0aa6ad21cc1e.png)

I'm having the same issues with chests, beds, enchanting tables, and signs. It's very noticeable here.
Using SEUS Renewed v1.01

**Comment by KaiAF** [comment]
update to pre23. this should have been fixed

**Comment by OblivionFall** [comment]
I should clarify that my screenshot was taken on pre23. The problem persists.
![2021-06-27_17 03 10](https://user-images.githubusercontent.com/86563416/123560751-d204cd00-d769-11eb-9950-7bc5dd498620.png)

**Comment by KaiAF** [comment]
See if this was fixed in the latest preview version. (pre 26)

**Comment by fayer3** [comment]
the lighting issue might now be fixed with pre28, please test if this is still an issue

**Comment by Lyky35** [comment]
Fixed for normals

underwater appears to be still an issue
![image](https://user-images.githubusercontent.com/36609323/125531764-b77ed397-b736-4c49-8ad0-9820d702f49d.png)
