### ISSUE TITLE
[Shader Issue] Sky Flickering and Turning Black.

### ISSUE THREAD

**Issue by BuckPrivate** [sp614x/optifine#5925]
**Description of Issue**
Sky seemingly randomly turns black when looking at sky, though sometimes not even whilst looking at the sky. Issue seems to occur when looking at one of several points radiating out from the sun while the sun sets. These points are not visible, but you'll know you're looking at one when the sky changes. The points do not stay in one place, but rather follow the sun as it sets, and you can follow them to keep the sky black.

![2021-06-28_14 05 28](https://user-images.githubusercontent.com/60932187/123692174-1e104a00-d81c-11eb-8eca-6c74b3492491.png)
![2021-06-28_14 05 25](https://user-images.githubusercontent.com/60932187/123692187-2072a400-d81c-11eb-8874-5d00c1984636.png)

**Steps to Reproduce**
1. Launch Minecraft
2. Wait until dusk, then focus crosshairs at a number of points around the sun
3. Observe the sky flashing black, then return to normal as the sun sets.
4. Sky can remain black by following the point as the sun sets.

**OptiFine Version**
1.17 HD U G9 pre24

**Installation Method**
Standalone installer

**Other Installed Mods**
Sildur's Vibrant Shaders 1.29 Extreme w/ Volumetric Lighting

**F3 Debug Screenshot**
![2021-06-28_14 15 16](https://user-images.githubusercontent.com/60932187/123691544-5ebb9380-d81b-11eb-9e35-596334e7817f.png)
 
**Prior Testing**
- Does this happen in Vanilla without OptiFine?
No

**Additional Information**
Smaller, similar black shadows are present occasionally when aiming at blocks during a similar time of day, but are limited to the borders of the block aimed at. Turning "Fast Render" off fixes this, but has no effect on the sky blackening issue.

**Comment by Whitelisted1** [comment]
I would assume this would be a shader issue, considering shaders are still pre and are not finished for optifine yet, so I would wait for that to come out

**Comment by KaiAF** [comment]
Try turning off Render Regions and Smooth FPS and see if that helps.

**Comment by BuckPrivate** [comment]
Turning off Render Regions and Smooth FPS seems to have had no effect. It seems to only happen when the sun is setting, and the stars are just starting to come out. Once the stars are out, though, the sky will not turn black or flicker.

**Comment by KaiAF** [comment]
See if this was fixed in the latest preview version. (pre 26)

**Comment by BuckPrivate** [comment]
Currently running pre32, I haven't noticed it yet. The linked issue (#5910) still does happen, though.

**Comment by BuckPrivate** [comment]
Just wanted to see if you guys are still tracking this issue. It's still ongoing in pre33.

**Comment by CaseRocker** [comment]
I have tested silders vibrant shader in the latest Optifine build for pre33 against the latest build for Iris and the same sky going Black is not happening with the change of day in Iris but it IS happening in Optifine. Also in the End the sky is bright white in Optifine but not in Iris. So it would seem this is an Optifine issue and not a shader issue.

**Comment by CaseRocker** [comment]
![Minecraft_ 1 17 - Multiplayer (3rd-party Server) 8_17_2021 7_44_14 PM](https://user-images.githubusercontent.com/89363011/130373379-d0c4061a-2f85-4b6b-8c97-8a4ac96d7be6.png)

This is the End sky when using Optifine.

**Comment by fayer3** [comment]
the issue here, for the black sky, is that optifine writes the fog color to colortex0,
even though sildur discards the sky by writing vec4(0.0) to gl_FragData[0] in gbuffers_skybasic.

**Comment by Sildurs-shaders** [comment]
Fixed by filling alpha with 1.0 in skybasic.

**Comment by SkarletShadows** [comment]
Still having this issue with shaders causing black sky as described by OP;
Optifine Version: OptiFine_1.17.1_HD_U_G9
Shader: Sildurs Vibrant Shaders v1.29 {Any}
Resource pack: Mizunos 16 Craft JE_1.17.1-1.0

**Comment by SkarletShadows** [comment]
I don't see that setting anywhere? or I'm misunderstanding something

**Comment by fayer3** [comment]
you misunderstood. The fix is on the shader side, and will be included in the next version of sildurs vibrant shader.
