### ISSUE TITLE
[bug] [shaders] 1.18 frustum.culling option in shaders.properties not functional

### ISSUE THREAD

**Issue by fayer3** [sp614x/optifine#6410]
## Description of Issue
disabling frustum culling with `frustum.culling=false` doesn't do anything in 1.18, works fine in 1.17

## Steps to Reproduce
1. use attached shader, or any that relies on frustum culling being disabled
2. see that chunks disappear when looking away

## OptiFine Version
1.18-pre1-OptiFine_HD_U_H3_pre2

## Installation Method
standalone installer

## F3 Debug Screenshot
![grafik](https://user-images.githubusercontent.com/8282299/143903788-bedc444b-c52c-4f76-9d19-5a27bfd8169d.png)

## Additional Information
shader used for testing:
[360.zip](https://github.com/sp614x/optifine/files/7619483/360.zip)

**Comment by fayer3** [comment]
update:
looks like the toggle does work for entities, those all get rendered when disabling the culling.
the terrain gets culled regardless of the option.

**Comment by sp614x** [comment]
Should be fixed in latest version

**Comment by fayer3** [comment]
does latest version mean an unreleased version? because it doesn't work with 1.18.1 HD U H4

**Comment by fayer3** [comment]
does still happen with 1.18.1 HD U H5 pre1
does this only not work for me?

**Comment by sp614x** [comment]
This time really fixed.
