### ISSUE TITLE
OptiFine and Tinker's Construct Crashing Problem

### ISSUE THREAD

**Issue by Cicopath** [sp614x/optifine#6607]
As Tinker's Construct has released an alpha release for 1.18.1, my brothers and I were excited to try it out. However, when wearing certain items, the client crashes. After removing OptiFine, the issue disappears, and I can wear the items without my client crashing. Prior to the installation of Tinker's Construct, there have been no crashes; and after installing Tinker's Construct and removing OptiFine, there have also been no crashes. It appears to only occur when Tinker's Construct and OptiFine are installed together.

## Steps to Reproduce
1. Have both Tinker's Construct and OptiFine installed
2. Wear the Traveler's Goggles or Plate armor

The crash occurs when you wear the item. Without OptiFine, the crash does not occur. In fact, there have been other reports related to this. [See related issues here.](https://github.com/SlimeKnights/TinkersConstruct/issues/4734)

## OptiFine Version
OptiFine 1.18.1 HD U H4

## Installation Method
I dropped the .jar file into my mods folder.

## Fabric/Forge Version
39.0.66

## Other Installed Mods
Ars Nouveau
Balm
Building Gadgets
Cloth Config API
Crossbowverhaul
Cucumber
Curios
Dungeon Crawl
Dungeons Arise
Farmer's Delight
MrCrayfish's Furniture
GeckoLib
JEI
Mantle
Mystical Agriculture
NoFog
Patchouli
Terralith
Waystones

## Log Files/Crash Reports
There are two crash logs: One where PLAYER3 wears the goggles then crashes, and one where PLAYER2 loads my character (I do not have OptiFine installed at this point, and can currently wear the goggles) and crashes.
https://paste.gg/p/anonymous/a1b208c586414fcaa17a4233c4ee9338

Please forgive me as to not answering the other questions, as I have already removed OptiFine and everything is going well in the server now.

**Comment by Cicopath** [comment]
The only reason I post this here is because it appears to be an issue that the SlimeKnights developers cannot fix, and is instead an OptiFine-related issue.

**Comment by KnightMiner** [comment]
For more context, this issue is caused before Tinkers' Construct makes use of forge PR 8349. Optifine due to the way they change vanilla code deletes that part of that PR in favor of the original code. This would not happen if Optifine just patched classes in a way that does not conflict with new forge changes.

If the Optifine dev does not wish to switch to patches, it is of my opinion they should either:
* Have a specific list of forge versions they support and not launch otherwise
* Be constantly watching forge pull requests so a new optifine version can be released same day to resolve conflicting patches

Otherwise Optifines poor practices will keep making more work for the mod devs. If you don't wish to properly support mods, don't make a forge version.

**Comment by Cicopath** [comment]
This seems to have gone unaddressed for a few days. Hmm...

**Comment by Flexz9** [comment]
I've noticed the same issue:
[crash-2022-02-13_20.23.08-client.txt](https://github.com/sp614x/optifine/files/8056488/crash-2022-02-13_20.23.08-client.txt)

**Comment by KnightMiner** [comment]
Yeah, a lot of people noticed the same issue. The fact remains there is nothing Tinkers Construct can do about this crash, and I highly doubt Optifine will fix it anytime soon. I would encourage uninstalling the mod in favor of a performance mod where the author actually respond to issues on their issue tracker. Some suggestions [are here]https://github.com/NordicGamerFE/usefulmods/blob/main/Performance/Performance118.md)

**Comment by IvorAmlug** [comment]
Has this been noticed?

**Comment by Cicopath** [comment]
No. It has, in fact, not been noticed, and likely will not be noticed for a while.

**Comment by IvorAmlug** [comment]
Yikes

**Comment by NovaLynxie** [comment]
I use Optifine for shader support since I don't know of any other mods that will handle this. Having to remove that in favour of modpack stability is really not ideal. Really hope this gets fixed at some point in the future.

**Comment by IvorAmlug** [comment]
Well they added the Labels so at least someone saw it ig but me too I love my shaders but so do i love TC

**Comment by ShinyPorygon** [comment]
> I use Optifine for shader support since I don't know of any other mods that will handle this. Having to remove that in favour of modpack stability is really not ideal. Really hope this gets fixed at some point in the future.

Vanilla shaders exist and have the potential to do everything that OptiDumpsterFire does without sending your game into pure hell 
https://github.com/bradleyq/mc_vanilla_shaders/releases/tag/v2.3
I suggest this as I use it without issues with mods. You just turn in fabulous graphics and add it as a resource pack! It will say made for an older version but works fine.

**Comment by Baldur9** [comment]
I have a work-around: If you want to use both Tinker's with armor and Optifine then install [Cosmetic Armor Reworked](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked). I am currently using 1.18.1, Optifine & Sildur's shaders and got it to work so long as you equip the cosmetic armor first.

**Comment by sp614x** [comment]
Fixed in H6 for 1.8.1.

**Comment by ciserman** [comment]
My game is still crashing with the new Optifine version when I open the Smeltery interface:
[crash-2022-03-25_14.35.44-client.txt](https://github.com/sp614x/optifine/files/8353067/crash-2022-03-25_14.35.44-client.txt)

**Comment by Lightman314** [comment]
> My game is still crashing with the new Optifine version when I open the Smeltery interface: [crash-2022-03-25_14.35.44-client.txt](https://github.com/sp614x/optifine/files/8353067/crash-2022-03-25_14.35.44-client.txt)

That crash refers to sophisticated backpacks not tinkers armor, and should thusly be reported as it's own issue (likely to sophisticated backpacks until such a time as they tell you that it's a optifine issue, not an issue on their end). From my experience the tinker's armor compatiblity issue has been properly fixed, and is now working as intended for which I'd like to thank the optifine devs for properly fixing the issue :)
