### ISSUE TITLE
[Bug] 1.19: Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by derklaro** [sp614x/optifine#6858]
## Description of Issue
The client crashes with an IllegalStateException sometimes when normally moving trough a world.

## Steps to Reproduce
1. Join a singleplayer world or server
2. Fly around with an elytra (For me it only happened then)

## OptiFine Version
Preview OptiFine 1.19_HD_U_H8_pre1

## Installation Method
Using the standalone installer.

## Log Files/Crash Reports
https://gist.github.com/derklaro/1fc88ab7323276d696f105376c77e19b

## Prior Testing
Was playing with the vanilla client since the 1.19 release day and never encountered the issue before.

**Comment by derklaro** [comment]
I don't

**Comment by Clonedelta** [comment]
I am receiving the same crash report, however I am using a resource pack. 

Deactivating my resource pack resolved the issue. This is what I use: https://www.planetminecraft.com/texture-pack/excalibur/
I can provide the crash file as well if you want.

**Comment by Clonedelta** [comment]
That seems to be the case. 

Not all resource packs appear to be causing it though, small adjustments like the "Shield Corrections" resource pack are functioning when I use it. I'm not sure to what extent a resource pack would crash it.

Excalibur has a lot of custom models for stuff like ladders, rails, etc so I'm not sure what would contribute to that thread crash.

**Comment by Clonedelta** [comment]
I'm not sure I know what CTM is. Googling it, I see "Complete the Monument"?

**Comment by Clonedelta** [comment]
Shaders are confirmed to not work right now: https://twitter.com/OptiFineNews/status/1542131372290179078?s=20&t=T8Q8Eq-iuIZyijd2v2iszg

**Comment by Trottero** [comment]
@Clonedelta I am fully aware that shaders are currently not working, I did however want to mention that it was selected, as it might influence the way that certain things would be handled.

After my second crash I toggled `Conntected Textures` from `fancy` to `off`. Haven't crashed yet.

**Comment by H4ML-Aplek** [comment]
same happens for me too
i used optifine with and without a pack and the issue occured anyways. Same for a firend of mine

**Comment by Ceelbc** [comment]
Same problem, but now it is wit creative flight and with the John Smith Legacy texture pack. Without optifine it is fine even with the texture pack.

**Comment by EmmyAnn** [comment]
Same problem, I use a few resorce packs and it crashes when I'm walking around or swimming.

**Comment by YaCCBoy** [comment]
I think the problem is linked to connected textures. While they were disabled, I had no issues. However, enabling them caused the game to crash, no matter if they were set to fast or fancy. This happened regardless of if I had a resource pack on or not.

Here is my most recent crash report for reference:
[crash-2022-06-29_20.40.45-client.txt](https://github.com/sp614x/optifine/files/9015474/crash-2022-06-29_20.40.45-client.txt)

**Comment by Heanthor** [comment]
Similar crash here, similar stack trace
[crash-2022-06-29_22.02.30-client.txt](https://github.com/sp614x/optifine/files/9015887/crash-2022-06-29_22.02.30-client.txt)

**Comment by DragonsScales** [comment]
Same thing happened to me without any shaders or resource packs. and it was just while loading in the world while it's raining.

**Comment by Ceelbc** [comment]
For me it even crashes without flying. I only deleted a wall block (Altered with the debug stick). (OptiFine version: OptiFine HD U H8 pre2)
[crash-2022-07-01_12.18.56-client.txt](https://github.com/sp614x/optifine/files/9028117/crash-2022-07-01_12.18.56-client.txt)

**Comment by PurlzBeforeSwine** [comment]
Have you guys tried disabling Connected Textures?

**Comment by 4a454646** [comment]
Can confirm, the only fix I have found is to completely disable Connected Textures, which is a bummer since I use a pack which relies on them.

**Comment by Migats** [comment]
Can confirm. I was using a resourcepack I made myself. Fully checked the whole pack and nothing is wrong.

**Comment by videosambo** [comment]
Same issue persist on version preview_OptiFine_1.19_HD_U_H8_pre3

I don't have any resource packs on and I just joined to my server and client crashed right away.

[https://pastebin.com/Ncn6PUQ6](https://pastebin.com/Ncn6PUQ6)

**Comment by KaiAF** [comment]
Update:
![image](https://user-images.githubusercontent.com/60985521/177224613-4e7ab03a-2135-4e2c-ae14-3bd101c8c79c.png)

**Comment by KaiAF** [comment]
Should be fixed in the latest preview

**Comment by TikiGuy156** [comment]
Having an issue where it still crashes even though Connected Textures have been turned off in the video quality settings.
[crash-2023-02-16_13.54.37-client.txt](https://github.com/sp614x/optifine/files/10760742/crash-2023-02-16_13.54.37-client.txt)
