### ISSUE TITLE
[Crash] Can't launch Optifine with Forge 1.18.2 - 40.1.54 or above

### ISSUE THREAD

**Issue by Lucreeper74** [sp614x/optifine#7009]
## Description of Issue
I have already noticed when updating the Forge version of my modpack (required for some mods) that Optifine crashes my game when I launch a single player world. Then I quickly noticed that Optifine itself was the problem because I tested it on its own with different versions of forge. I couldn't run optifine only with 40.1.54 or higher.

## Steps to Reproduce
1. What do you do...
2. ...to find this bug?

## OptiFine Version
Optifine 1.18.2 - HD U H7 (Latest for 1.18.2)

## Installation Method
Jar into Mods folder without any others mods.

## Fabric/Forge Version
Issue with Forge 1.18.2 - 40.1.54 or Higher
(I was in 40.1.67 for the crash report)

## Log Files/Crash Reports
Crash report : https://pastebin.com/P3fRfUHZ
Log : https://pastebin.com/EkaEsF6z

## F3 Debug Screenshot
I can't launch singleplayer world so...

## Additionnal
Thx u for reading my problem, and thanks in advance!

**Comment by Okimo** [comment]
To be exact latest Forge version that doesn't crash is "40.1.57" after that its the same crash.

**Comment by moninformateur** [comment]
> To be exact latest Forge version that doesn't crash (in my case) is "40.1.57" after that its the same crash.

Same here. Let's hope they'll update Optifine to work with those changes.

**Comment by HellishINC** [comment]
Optifine is crashing because forge removed a method that it depends on.

```
java.lang.NoSuchMethodError: 'void net.minecraft.server.level.DistanceManager.addRegionTicket(net.minecraft.server.level.TicketType, net.minecraft.world.level.ChunkPos, int, java.lang.Object, boolean)'
	at net.minecraft.server.level.ServerChunkCache.addRegionTicket(ServerChunkCache.java:429) ~[client-1.18.2-20220404.173914-srg.jar%2361!/:?] {re:classloading,pl:accesstransformer:B}
```

**Comment by kingOf0** [comment]
![image](https://user-images.githubusercontent.com/44327892/180246242-45e31d61-0f44-4a24-a8da-9dd3d422bd11.png)
Actually 40.1.57 works. But 40.1.60 and 40.1.68 doesn't seem to work.

**Comment by Okimo** [comment]
> ![image](https://user-images.githubusercontent.com/44327892/180246242-45e31d61-0f44-4a24-a8da-9dd3d422bd11.png) Actually 40.1.57 works. But 40.1.60 and 40.1.68 doesn't seem to work.

As I said and other two before you confirmed :)

**Comment by labradoe** [comment]
Just went to start playing on 1.18.2 and discovered this issue. Hopefully this issue has been acknowledged and a fix is in the works.

**Comment by SaltSouls** [comment]
Yeah, same problem here. Really hoping this gets fixed, especially with all the recent issues with 1.19 as a whole, not just including the lack of big mods currently available for it.

**Comment by Archasmiel** [comment]
Same error, even if trying to launch only-Optifine: 
https://pastebin.com/jCeqn0FC
https://pastebin.com/nSihVauL

**Comment by HellishINC** [comment]
"Me too"ing this issue does not contribute to the problem.

If you want to add your voice, add a reaction to the original (or other helpful) post.

All you're doing is spamming everyone here's inbox.

**Comment by BlackEagle73** [comment]
Some new for possible patch ?

**Comment by Okimo** [comment]
Tbh its going to be ignored as every other bugs reports written here on github.
As they are "working" right now on 1.19 and what's in previous versions they ignore.
So they usually end up carrying old bugs with them too.

**Comment by WebDragon** [comment]
The annoying part of that is there are modpacks on 1.18.2 that we can no longer use Optifine for because of this. As well as there are going to be some people who don't want to move to 1.19 due to the ongoing kerfluffle over the whole reporting system.

**Comment by labradoe** [comment]
I made the switch over to Rubidium and Oculus. Not having any issues there and runs a bit better, imo. Good luck waiting for this one!

**Comment by sp614x** [comment]
Fixed in H8_pre1.

**Comment by jvsdr** [comment]
**For future users don't have this issue...** Just grab the preview version, and it works! PS: Keep update cause it's a preview version lol

![image](https://user-images.githubusercontent.com/10999602/186825971-e09bb467-31d3-42a6-abda-63bca5455cad.png)

**Comment by TheLaddd** [comment]
How am I still experiencing this issue? I downloaded the latest preview on the latest version of Forge for 1.18.2 (Forge version 40.1.80). I also tried on Forge 40.1.73 and it still crashed with the same error. This is with only Optifine downloaded, so it is not another mod. Any solution? Do I select a specific Forge version?

**Comment by AgentCPU0** [comment]
I tried the latest previes. My game still crashes

**Comment by KitLoaf1** [comment]
Is there a version that works with Forge 40.1.79?

**Comment by KillNagaThul** [comment]
only OptiFine HD U H9 pre1 work with forge 40.1.79 other issues, you need to check each Mods installed...
if you want to play with the latest version of forge you should consider replacing optifine with another mod, for example Oculus

**Comment by WebDragon** [comment]
the problem with that arises when a texturepack (Misa's Realistic) + BSL shaders are specifically tuned to work together with optifine in particular. The lack of a fix for this since July is particularly annoying.

**Comment by AgentCPU0** [comment]
Why was this issue closed when it's very obvious it hasn't been fixed? Are the OptiFine devs just shrugging their shoulders and giving up? They know it's an isssue because people are reporting it
