### ISSUE TITLE
[Shader] at_velocity broken in 1.20.6

### ISSUE THREAD

**Issue by GeForceLegend** [sp614x/optifine#7701]
## Description of Issue

`at_velocity` does not working correctly on Optifine 1.20.6, causing visual artifacts on entities when shader is using `at_velocity` to calculate motion vector. It works fine on 1.20.1 I6.

## Steps to Reproduce

1. Using shaderpack SEUS PTGI HRR3 with Optifine 1.20.6
2. Join a world and moving, and see if entities get extremely blur
![2024-08-06_08 53 03](https://github.com/user-attachments/assets/71aca42c-5d46-43ee-82ff-fb85d069abd6)

## OptiFine Version

1.20.6 I9 Pre1

## Installation Method

Standalone

## F3 Debug Screenshot
![2024-08-06_08 57 16](https://github.com/user-attachments/assets/73ba06d1-ee37-40d0-b617-d6feb263a797)

**Comment by GeForceLegend** [comment]
Still exists in 1.21 Pre8. Hope it can get fixed before stable release of Optifine 1.21.

**Comment by sp614x** [comment]
Probably fixed with #7714

**Comment by GeForceLegend** [comment]
Tested with HRR3 and still not get fixed, this started happen on 1.20.6 (not sure if 1.20.4 also affected), so might be nothing related to wrong `at_midBlock` that only exist on 1.21 previews

**Comment by sp614x** [comment]
Fixed, coming in next preview.
