### ISSUE TITLE
[1.21.10 Bug] CIT item icons do not function

### ISSUE THREAD

**Issue by SeaOfPixels** [sp614x/optifine#7939]
## Description of Issue
CIT icons (textures in the hand and gui) do not function. Note that CIT worn models, such as armor models and elytra models, do function correctly. Please note when using my pack to test: my pack has Vanilla CIT support for its non-armor/elytra item renames (such as "Emerald Sword"), so it may not be a good test pack for fixing that aspect.

## Steps to Reproduce
1. Install [my pack](https://legacy.curseforge.com/minecraft/texture-packs/newdefaultplus/files/6696432)
2. Activate it in-game
3. Attempt to rename an armor set "Fortified Diamond Armor Helmet", "Fortified Diamond Armor Chestplate", "Fortified Diamond Armor Leggings", "Fortified Diamond Armor Boots".
4. Note how the CIT does not apply to the items in the inventory, but does to the worn model.
5. Attempt to rename an elytra "Minecon 2011 Elytra".
6. Note how the CIT does not apply to the item in the inventory, but does to the worn model.

## Screenshots
![Image](https://github.com/user-attachments/assets/0735e0fe-2ea6-4045-a6b7-d7c1d63cb5d9)
![Image](https://github.com/user-attachments/assets/b273c66c-b0d4-47b0-b226-667e883d4322)

## OptiFine Version
preview_OptiFine_1.21.6_HD_U_J6_pre2, preview_OptiFine_1.21.6_HD_U_J6_pre3, Preview OptiFine 1.21.8_HD_U_J6_pre14, OptiFine 1.21.10_HD_U_J7_pre3

**Comment by ZenithRogue** [comment]
Something to note for @sp614x, items in slots are now rendered once to an atlas, rather than drawn every time.

**Comment by Emfire12345** [comment]
Still an issue as of Preview OptiFine 1.21.8_HD_U_J6_pre13

**Comment by minthousebuilder** [comment]
This is now even worse, it now loads a random part of the atlas per item type, and not even a whole tile, just a part of one (at least on a 64x64 pack, seems to display a 16x32 area, stretched.)

Not sure exactly when this new behaviour started but it's definitely there on 1.21.11_HD_U_J8_pre4.

These should all be diamond pickaxes at various levels of durability. 
Instead, they all use the same random part of the atlas (in this case somewhere around the brewing stand by the look of it). 
Changing the order of items in the inventory will alter which CIT texture it attempts to load, however it is never successful in finding any, it just changes which (seemingly) random atlas location it uses.
<img width="388" height="327" alt="Image" src="https://github.com/user-attachments/assets/3739aba2-13fd-405b-9445-dd777cfb7ad1" />
(To get it to at least try to render the CIT in the GUI, items have to be enchanted)

**Comment by SeaOfPixels** [comment]
Can confirm.

> This is now even worse, it now loads a random part of the atlas per item type, and not even a whole tile, just a part of one (at least on a 64x64 pack, seems to display a 16x32 area, stretched.)
> 
> Not sure exactly when this new behaviour started but it's definitely there on 1.21.11_HD_U_J8_pre4.
> 
> These should all be diamond pickaxes at various levels of durability. Instead, they all use the same random part of the atlas (in this case somewhere around the brewing stand by the look of it). Changing the order of items in the inventory will alter which CIT texture it attempts to load, however it is never successful in finding any, it just changes which (seemingly) random atlas location it uses. <img alt="Image" width="388" height="327" src="https://private-user-images.githubusercontent.com/80045916/534799829-3739aba2-13fd-405b-9445-dd777cfb7ad1.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjgzMTQ0MDgsIm5iZiI6MTc2ODMxNDEwOCwicGF0aCI6Ii84MDA0NTkxNi81MzQ3OTk4MjktMzczOWFiYTItMTNmZC00MDViLTk0NDUtZGQ3NzdjZmI3YWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMTEzVDE0MjE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NDRkYzdlODdjNTA1NTY5M2NjMjU3YjkwMDYzZGExZTE2MzA0MWRjZTY5NjE5MGJiMmIzYzRiNjNjNGI0NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J7dhAqy4n1CRK-FgRVkMSUhX31SrgEF8vbQYKHHpiJk"> (To get it to at least try to render the CIT in the GUI, items have to be enchanted)

**Comment by sp614x** [comment]
Should be fixed in 1.21.11 pre7.

**Comment by SeaOfPixels** [comment]
> Should be fixed in 1.21.11 pre7.

#8095 was not fixed.

**Comment by minthousebuilder** [comment]
CIT type=potion still doesn't work (I appreciate this wasn't brought up before so perhaps wasn't on the radar)

And while we're on the subject, may I ask is there any chance of type=enchantment ever being reimplemented?
