### ISSUE TITLE
[shader] Using `dynamic/lightmap_1` in shader.properties broken in 1.21.4

### ISSUE THREAD

**Issue by GeForceLegend** [sp614x/optifine#7961]
## Description of Issue

When using `minecraft:dynamic/lightmap_1` in shaders.properties, to use light map in deferred rendering pipeline, it will result in a black and purple error texture, instead of expected light map texture.

Error texture when tried using light map texture in deferred pipeline in 1.21.4
<img width="1496" height="967" alt="Image" src="https://github.com/user-attachments/assets/d8cd4a08-71f2-4b18-9929-e36d76a27d36" />

## Steps to Reproduce

1. Create a shaderpack, bind light map to certain colortex, and use it in deferred pipeline
2. Just output it or using capture softwares and see it being error texture

## OptiFine Version

1.21.4 J4 Pre2

## Installation Method

Standalone

## Log Files/Crash Reports

Log said `[Shaders] Custom texture: texture.composite.colortex7 = minecraft:dynamic/lightmap_1`, but in capture it's error texture

## F3 Debug Screenshot

Was using my own test shaders so the scene output has nothing related to this issue. Only to provide F3 info.
<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/76dcf919-136c-4cb6-8263-913d75d7e29a" />

## Additional Information

I believe this is an oversight as vanilla changed light map calculation in 1.21.2 and Optifine 1.21.1 works fine. Light map texture in gbuffer is also correct (If just uses `uniform sampler2D lightmap;`. If doing similar thing like binding light map to colorotex7 in gbuffer, it will be block atlas texture instead of error texture or light map)

**Comment by GeForceLegend** [comment]
Still exists in 1.21.8 J9 pre9

**Comment by sp614x** [comment]
Fixed, coming in next preview

**Comment by GeForceLegend** [comment]
Dynamic lightmap is still incorrect. It's now pure white, instead of being correct or being purple and black error texture.

<img width="1393" height="827" alt="Image" src="https://github.com/user-attachments/assets/705f9d20-2568-47ea-8a2c-99b12ccfb2b4" />
