### ISSUE TITLE
[Shaders] Hand visual bug on FOV change

### ISSUE THREAD

**Issue by JoeTrox452** [sp614x/optifine#7970]
## Description of Issue

When using a shader pack and you change the FOV option, your hand does not follow the camera like it does when shaders are not enabled. With the 3 packs I've tried (complementary, Seus, and this one pack named John? idk), the hand is like it's locked in place and the camera moves back and forth with an FOV change. With shaders disabled, the hand moves with the camera as the FOV changes. Interestingly, when using the debug shaders option, the hand does something else, above FOV 103 it starts clipping into the ground.

See bottom for detailed screenshots

## Steps to Reproduce

1. Install Complementary Unbound 5.5.1 (latest release) or any other shader pack
2. Change the FOV to quake pro
3. Notice hand doesn't move with camera

## OptiFine Version

preview_OptiFine_1.21.8_HD_U_J6_pre12

## Installation Method

Standalone installation

## Log Files/Crash Reports

[latest.log](https://github.com/user-attachments/files/21563081/latest.log)

## F3 Debug Screenshot

<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/0264b7e9-cc3c-4baf-9d46-ca21b6ee266a" />

## Prior Testing

Does not happen with shaders disabled

### Complementary shaders 70 FOV
<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/43716b3e-fc96-4a33-8283-71af3b33fe82" />

### Complementary shaders 110 FOV (quake pro)
<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/fd684a8f-8258-4420-b2df-1333c4526b71" />

### Complementary shaders 40 FOV
<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/2c944567-3c60-4797-b4d2-3a9bbbf9221d" />

### Seus shaders 70 FOV
<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/8d31365e-0e68-4ed6-90c7-645a0efc0bce" />

### Seus shaders 40 FOV
<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/367cf3f0-ba72-48ef-a0b9-6d001fe28cf7" />

### Seus shaders 110 FOV
<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/c05486b1-b401-4465-b13f-0155fd3f253f" />

### Debug shaders 70 FOV
<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/b631a3f9-ac43-48e9-85f6-d2555daf1b54" />

### Debug shaders 30 FOV
<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/e2185b85-b770-45b3-b20b-98b3402ff075" />

### Debug shaders 110 FOV
<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/5b95dcc3-98e3-4eea-a108-7a0e06e09a3d" />

**Comment by GeForceLegend** [comment]
Same as #7965 , that issue is still exists though sp614x said it was fixed.

**Comment by sp614x** [comment]
Reproduced with Complementary Unbound 5.5.1

**Comment by sp614x** [comment]
Fixed, coming in next preview

**Comment by JoeTrox452** [comment]
Issue is still present in standalone installation of preview_OptiFine_1.21.8_HD_U_J6_pre13

Screenshot of issue with F3 on Complementary Unbound 5.5.1, 110 FOV (and also speed 2)
<img width="1920" height="1017" alt="Image" src="https://github.com/user-attachments/assets/c9376975-4e4c-47eb-8ce0-ba86aa4a6bb8" />

Log file:
[latest.log](https://github.com/user-attachments/files/21570439/latest.log)
